-- Marketplace database hardening.
--
-- Neon is now the production source of truth. This migration makes the
-- imported SQLite-shaped serving schema safe for incremental writes by adding
-- database-generated IDs, stable public IDs, lifecycle metadata, audit tables,
-- search refresh functions, and transaction-safe mutation helpers.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

DO $$
BEGIN
    IF to_regclass('__CANONICAL_SCHEMA__.locations') IS NULL THEN
        RAISE EXCEPTION 'Missing %.locations. Run the Postgres bootstrap before applying serving-schema migrations.', '__CANONICAL_SCHEMA__';
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS __CANONICAL_SCHEMA__.accounts (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email        TEXT,
    display_name TEXT,
    role         TEXT NOT NULL DEFAULT 'clinic',
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_accounts_email_lower
    ON __CANONICAL_SCHEMA__.accounts(lower(email))
    WHERE email IS NOT NULL AND email <> '';

DO $$
DECLARE
    schema_name TEXT := '__CANONICAL_SCHEMA__';
    target_table TEXT;
    max_id BIGINT;
    sequence_name TEXT;
BEGIN
    FOREACH target_table IN ARRAY ARRAY[
        'sources',
        'organizations',
        'locations',
        'practitioners',
        'documents',
        'categories',
        'treatments',
        'affiliations',
        'treatment_aliases',
        'offerings',
        'tags',
        'entity_tags',
        'source_records',
        'images',
        'reviews',
        'external_reviews',
        'unmapped_terms'
    ] LOOP
        IF to_regclass(format('%I.%I', schema_name, target_table)) IS NULL THEN
            CONTINUE;
        END IF;

        IF EXISTS (
            SELECT 1
            FROM information_schema.columns
            WHERE table_schema = schema_name
              AND table_name = target_table
              AND column_name = 'id'
              AND is_identity = 'NO'
              AND column_default IS NULL
        ) THEN
            EXECUTE format(
                'ALTER TABLE %I.%I ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY',
                schema_name,
                target_table
            );
        END IF;

        SELECT pg_get_serial_sequence(format('%I.%I', schema_name, target_table), 'id')
        INTO sequence_name;

        IF sequence_name IS NOT NULL THEN
            EXECUTE format('SELECT COALESCE(MAX(id), 0) FROM %I.%I', schema_name, target_table)
            INTO max_id;

            IF max_id > 0 THEN
                PERFORM setval(sequence_name::regclass, max_id, true);
            ELSE
                PERFORM setval(sequence_name::regclass, 1, false);
            END IF;
        END IF;
    END LOOP;
END $$;

DO $$
DECLARE
    schema_name TEXT := '__CANONICAL_SCHEMA__';
    target_table TEXT;
BEGIN
    FOREACH target_table IN ARRAY ARRAY[
        'organizations',
        'locations',
        'practitioners'
    ] LOOP
        EXECUTE format('ALTER TABLE %I.%I ADD COLUMN IF NOT EXISTS public_id UUID', schema_name, target_table);
        EXECUTE format('UPDATE %I.%I SET public_id = gen_random_uuid() WHERE public_id IS NULL', schema_name, target_table);
        EXECUTE format('ALTER TABLE %I.%I ALTER COLUMN public_id SET DEFAULT gen_random_uuid()', schema_name, target_table);
        EXECUTE format('ALTER TABLE %I.%I ALTER COLUMN public_id SET NOT NULL', schema_name, target_table);
        EXECUTE format(
            'CREATE UNIQUE INDEX IF NOT EXISTS %I ON %I.%I(public_id)',
            'idx_' || target_table || '_public_id',
            schema_name,
            target_table
        );
    END LOOP;
END $$;

DO $$
DECLARE
    schema_name TEXT := '__CANONICAL_SCHEMA__';
    target_table TEXT;
BEGIN
    FOREACH target_table IN ARRAY ARRAY[
        'organizations',
        'locations',
        'practitioners',
        'documents',
        'affiliations',
        'offerings',
        'images',
        'reviews'
    ] LOOP
        EXECUTE format('ALTER TABLE %I.%I ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT ''active''', schema_name, target_table);
        EXECUTE format('ALTER TABLE %I.%I ADD COLUMN IF NOT EXISTS data_origin TEXT NOT NULL DEFAULT ''imported''', schema_name, target_table);
        EXECUTE format('ALTER TABLE %I.%I ADD COLUMN IF NOT EXISTS verification_status TEXT NOT NULL DEFAULT ''unverified''', schema_name, target_table);
        EXECUTE format('ALTER TABLE %I.%I ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT now()', schema_name, target_table);
        EXECUTE format('ALTER TABLE %I.%I ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT now()', schema_name, target_table);
        EXECUTE format('ALTER TABLE %I.%I ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ', schema_name, target_table);
        EXECUTE format('ALTER TABLE %I.%I ADD COLUMN IF NOT EXISTS owner_account_id UUID', schema_name, target_table);
    END LOOP;
END $$;

DO $$
DECLARE
    schema_name TEXT := '__CANONICAL_SCHEMA__';
    target_table TEXT;
    constraint_name TEXT;
BEGIN
    FOREACH target_table IN ARRAY ARRAY[
        'organizations',
        'locations',
        'practitioners',
        'documents',
        'affiliations',
        'offerings',
        'images',
        'reviews'
    ] LOOP
        constraint_name := target_table || '_owner_account_fk';
        IF NOT EXISTS (
            SELECT 1
            FROM pg_constraint c
            JOIN pg_namespace n ON n.oid = c.connamespace
            WHERE n.nspname = schema_name
              AND c.conname = constraint_name
        ) THEN
            EXECUTE format(
                'ALTER TABLE %I.%I ADD CONSTRAINT %I FOREIGN KEY (owner_account_id) REFERENCES %I.accounts(id) ON DELETE SET NULL',
                schema_name,
                target_table,
                constraint_name,
                schema_name
            );
        END IF;

        constraint_name := target_table || '_status_valid';
        IF NOT EXISTS (
            SELECT 1
            FROM pg_constraint c
            JOIN pg_namespace n ON n.oid = c.connamespace
            WHERE n.nspname = schema_name
              AND c.conname = constraint_name
        ) THEN
            EXECUTE format(
                'ALTER TABLE %I.%I ADD CONSTRAINT %I CHECK (status IN (''active'', ''pending'', ''draft'', ''hidden'', ''deleted'')) NOT VALID',
                schema_name,
                target_table,
                constraint_name
            );
        END IF;
        EXECUTE format('ALTER TABLE %I.%I VALIDATE CONSTRAINT %I', schema_name, target_table, constraint_name);

        constraint_name := target_table || '_data_origin_valid';
        IF NOT EXISTS (
            SELECT 1
            FROM pg_constraint c
            JOIN pg_namespace n ON n.oid = c.connamespace
            WHERE n.nspname = schema_name
              AND c.conname = constraint_name
        ) THEN
            EXECUTE format(
                'ALTER TABLE %I.%I ADD CONSTRAINT %I CHECK (data_origin IN (''imported'', ''scraped'', ''manual'', ''owner'', ''system'')) NOT VALID',
                schema_name,
                target_table,
                constraint_name
            );
        END IF;
        EXECUTE format('ALTER TABLE %I.%I VALIDATE CONSTRAINT %I', schema_name, target_table, constraint_name);
    END LOOP;
END $$;

CREATE TABLE IF NOT EXISTS __CANONICAL_SCHEMA__.clinic_claims (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id       UUID NOT NULL DEFAULT gen_random_uuid(),
    account_id      UUID NOT NULL REFERENCES __CANONICAL_SCHEMA__.accounts(id) ON DELETE CASCADE,
    location_id     INTEGER REFERENCES __CANONICAL_SCHEMA__.locations(id) ON DELETE CASCADE,
    org_id          INTEGER REFERENCES __CANONICAL_SCHEMA__.organizations(id) ON DELETE CASCADE,
    status          TEXT NOT NULL DEFAULT 'pending',
    claim_method    TEXT,
    evidence        JSONB NOT NULL DEFAULT '{}'::jsonb,
    reviewed_by     UUID REFERENCES __CANONICAL_SCHEMA__.accounts(id) ON DELETE SET NULL,
    reviewed_at     TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT clinic_claims_public_id_unique UNIQUE(public_id),
    CONSTRAINT clinic_claims_target_required CHECK (location_id IS NOT NULL OR org_id IS NOT NULL),
    CONSTRAINT clinic_claims_status_valid CHECK (status IN ('pending', 'approved', 'rejected', 'revoked'))
);

CREATE INDEX IF NOT EXISTS idx_clinic_claims_account_status
    ON __CANONICAL_SCHEMA__.clinic_claims(account_id, status);

CREATE INDEX IF NOT EXISTS idx_clinic_claims_location
    ON __CANONICAL_SCHEMA__.clinic_claims(location_id)
    WHERE location_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS __CANONICAL_SCHEMA__.listing_submissions (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id          UUID NOT NULL DEFAULT gen_random_uuid(),
    account_id         UUID REFERENCES __CANONICAL_SCHEMA__.accounts(id) ON DELETE SET NULL,
    target_entity_type TEXT,
    target_entity_id   INTEGER,
    submission_type    TEXT NOT NULL,
    status             TEXT NOT NULL DEFAULT 'pending',
    payload            JSONB NOT NULL DEFAULT '{}'::jsonb,
    review_notes       TEXT,
    reviewed_by        UUID REFERENCES __CANONICAL_SCHEMA__.accounts(id) ON DELETE SET NULL,
    reviewed_at        TIMESTAMPTZ,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT listing_submissions_public_id_unique UNIQUE(public_id),
    CONSTRAINT listing_submissions_type_valid CHECK (submission_type IN ('create', 'update', 'delete', 'claim', 'merge')),
    CONSTRAINT listing_submissions_status_valid CHECK (status IN ('pending', 'approved', 'rejected', 'withdrawn', 'applied'))
);

CREATE INDEX IF NOT EXISTS idx_listing_submissions_status_created
    ON __CANONICAL_SCHEMA__.listing_submissions(status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_listing_submissions_target
    ON __CANONICAL_SCHEMA__.listing_submissions(target_entity_type, target_entity_id)
    WHERE target_entity_type IS NOT NULL AND target_entity_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS __CANONICAL_SCHEMA__.entity_change_events (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type TEXT NOT NULL,
    entity_id   INTEGER,
    action      TEXT NOT NULL,
    actor_type  TEXT NOT NULL DEFAULT 'system',
    actor_id    UUID,
    reason      TEXT,
    metadata    JSONB NOT NULL DEFAULT '{}'::jsonb,
    before_data JSONB,
    after_data  JSONB,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_entity_change_events_entity_created
    ON __CANONICAL_SCHEMA__.entity_change_events(entity_type, entity_id, created_at DESC);

CREATE OR REPLACE FUNCTION __CANONICAL_SCHEMA__.touch_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION __CANONICAL_SCHEMA__.audit_entity_change()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    actor_id_text TEXT;
    safe_actor_id UUID;
BEGIN
    actor_id_text := current_setting('fountain.actor_id', true);
    IF actor_id_text ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' THEN
        safe_actor_id := actor_id_text::uuid;
    END IF;

    INSERT INTO __CANONICAL_SCHEMA__.entity_change_events(
        entity_type,
        entity_id,
        action,
        actor_type,
        actor_id,
        before_data,
        after_data
    )
    VALUES (
        TG_TABLE_NAME,
        CASE WHEN TG_OP = 'DELETE' THEN OLD.id ELSE NEW.id END,
        lower(TG_OP),
        COALESCE(NULLIF(current_setting('fountain.actor_type', true), ''), 'system'),
        safe_actor_id,
        CASE WHEN TG_OP = 'INSERT' THEN NULL ELSE to_jsonb(OLD) END,
        CASE WHEN TG_OP = 'DELETE' THEN NULL ELSE to_jsonb(NEW) END
    );

    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;
    RETURN NEW;
END;
$$;

DO $$
DECLARE
    schema_name TEXT := '__CANONICAL_SCHEMA__';
    target_table TEXT;
BEGIN
    FOREACH target_table IN ARRAY ARRAY[
        'accounts',
        'organizations',
        'locations',
        'practitioners',
        'documents',
        'affiliations',
        'offerings',
        'images',
        'reviews',
        'clinic_claims',
        'listing_submissions'
    ] LOOP
        EXECUTE format('DROP TRIGGER IF EXISTS trg_touch_updated_at ON %I.%I', schema_name, target_table);
        EXECUTE format(
            'CREATE TRIGGER trg_touch_updated_at BEFORE UPDATE ON %I.%I FOR EACH ROW EXECUTE FUNCTION %I.touch_updated_at()',
            schema_name,
            target_table,
            schema_name
        );
    END LOOP;

    FOREACH target_table IN ARRAY ARRAY[
        'organizations',
        'locations',
        'practitioners',
        'documents',
        'affiliations',
        'offerings',
        'images',
        'reviews'
    ] LOOP
        EXECUTE format('DROP TRIGGER IF EXISTS trg_audit_entity_change ON %I.%I', schema_name, target_table);
        EXECUTE format(
            'CREATE TRIGGER trg_audit_entity_change AFTER INSERT OR UPDATE OR DELETE ON %I.%I FOR EACH ROW EXECUTE FUNCTION %I.audit_entity_change()',
            schema_name,
            target_table,
            schema_name
        );
    END LOOP;
END $$;

DELETE FROM __CANONICAL_SCHEMA__.search_index search_row
USING (
    SELECT ctid, row_number() OVER (PARTITION BY entity_type, entity_id ORDER BY ctid) AS duplicate_rank
    FROM __CANONICAL_SCHEMA__.search_index
) ranked
WHERE search_row.ctid = ranked.ctid
  AND ranked.duplicate_rank > 1;

CREATE UNIQUE INDEX IF NOT EXISTS idx_search_index_entity_unique
    ON __CANONICAL_SCHEMA__.search_index(entity_type, entity_id);

CREATE OR REPLACE FUNCTION __CANONICAL_SCHEMA__.refresh_search_index_for_location(p_location_id INTEGER)
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM __CANONICAL_SCHEMA__.locations l
        WHERE l.id = p_location_id
          AND l.status = 'active'
          AND l.deleted_at IS NULL
    ) THEN
        DELETE FROM __CANONICAL_SCHEMA__.search_index
        WHERE entity_type = 'location'
          AND entity_id = p_location_id;
        RETURN;
    END IF;

    INSERT INTO __CANONICAL_SCHEMA__.search_index(
        entity_type,
        entity_id,
        name,
        locality,
        country,
        treatments,
        specialties,
        tags
    )
    SELECT
        'location',
        l.id,
        COALESCE(l.name, org.canonical_name),
        l.locality,
        COALESCE(l.country_name, l.country_code),
        COALESCE((
            SELECT string_agg(DISTINCT COALESCE(t.canonical_name, o.raw_name), ' ' ORDER BY COALESCE(t.canonical_name, o.raw_name))
            FROM __CANONICAL_SCHEMA__.offerings o
            LEFT JOIN __CANONICAL_SCHEMA__.treatments t ON t.id = o.treatment_id
            WHERE o.location_id = l.id
              AND o.status = 'active'
              AND o.deleted_at IS NULL
              AND COALESCE(t.canonical_name, o.raw_name) IS NOT NULL
              AND COALESCE(t.canonical_name, o.raw_name) <> ''
        ), ''),
        '',
        COALESCE((
            SELECT string_agg(DISTINCT tg.facet || ':' || tg.value, ' ' ORDER BY tg.facet || ':' || tg.value)
            FROM __CANONICAL_SCHEMA__.entity_tags et
            JOIN __CANONICAL_SCHEMA__.tags tg ON tg.id = et.tag_id
            WHERE et.entity_type = 'location'
              AND et.entity_id = l.id
        ), '')
    FROM __CANONICAL_SCHEMA__.locations l
    LEFT JOIN __CANONICAL_SCHEMA__.organizations org ON org.id = l.org_id
    WHERE l.id = p_location_id
    ON CONFLICT (entity_type, entity_id) DO UPDATE SET
        name = EXCLUDED.name,
        locality = EXCLUDED.locality,
        country = EXCLUDED.country,
        treatments = EXCLUDED.treatments,
        specialties = EXCLUDED.specialties,
        tags = EXCLUDED.tags;
END;
$$;

CREATE OR REPLACE FUNCTION __CANONICAL_SCHEMA__.refresh_search_index_for_practitioner(p_practitioner_id INTEGER)
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM __CANONICAL_SCHEMA__.practitioners p
        WHERE p.id = p_practitioner_id
          AND p.status = 'active'
          AND p.deleted_at IS NULL
    ) THEN
        DELETE FROM __CANONICAL_SCHEMA__.search_index
        WHERE entity_type = 'practitioner'
          AND entity_id = p_practitioner_id;
        RETURN;
    END IF;

    INSERT INTO __CANONICAL_SCHEMA__.search_index(
        entity_type,
        entity_id,
        name,
        locality,
        country,
        treatments,
        specialties,
        tags
    )
    SELECT
        'practitioner',
        p.id,
        p.full_name,
        COALESCE((
            SELECT string_agg(DISTINCT l.locality, ' ' ORDER BY l.locality)
            FROM __CANONICAL_SCHEMA__.affiliations a
            JOIN __CANONICAL_SCHEMA__.locations l ON l.id = a.location_id
            WHERE a.practitioner_id = p.id
              AND a.status = 'active'
              AND a.deleted_at IS NULL
              AND l.status = 'active'
              AND l.deleted_at IS NULL
              AND l.locality IS NOT NULL
              AND l.locality <> ''
        ), ''),
        COALESCE((
            SELECT string_agg(DISTINCT COALESCE(l.country_name, l.country_code), ' ' ORDER BY COALESCE(l.country_name, l.country_code))
            FROM __CANONICAL_SCHEMA__.affiliations a
            JOIN __CANONICAL_SCHEMA__.locations l ON l.id = a.location_id
            WHERE a.practitioner_id = p.id
              AND a.status = 'active'
              AND a.deleted_at IS NULL
              AND l.status = 'active'
              AND l.deleted_at IS NULL
              AND COALESCE(l.country_name, l.country_code) IS NOT NULL
              AND COALESCE(l.country_name, l.country_code) <> ''
        ), ''),
        '',
        concat_ws(' ', p.primary_specialty, p.credentials, p.languages),
        COALESCE((
            SELECT string_agg(DISTINCT tg.facet || ':' || tg.value, ' ' ORDER BY tg.facet || ':' || tg.value)
            FROM __CANONICAL_SCHEMA__.entity_tags et
            JOIN __CANONICAL_SCHEMA__.tags tg ON tg.id = et.tag_id
            WHERE et.entity_type = 'practitioner'
              AND et.entity_id = p.id
        ), '')
    FROM __CANONICAL_SCHEMA__.practitioners p
    WHERE p.id = p_practitioner_id
    ON CONFLICT (entity_type, entity_id) DO UPDATE SET
        name = EXCLUDED.name,
        locality = EXCLUDED.locality,
        country = EXCLUDED.country,
        treatments = EXCLUDED.treatments,
        specialties = EXCLUDED.specialties,
        tags = EXCLUDED.tags;
END;
$$;

CREATE OR REPLACE FUNCTION __CANONICAL_SCHEMA__.refresh_search_index_for_document(p_document_id INTEGER)
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM __CANONICAL_SCHEMA__.documents d
        WHERE d.id = p_document_id
          AND d.status = 'active'
          AND d.deleted_at IS NULL
    ) THEN
        DELETE FROM __CANONICAL_SCHEMA__.search_index
        WHERE entity_type = 'document'
          AND entity_id = p_document_id;
        RETURN;
    END IF;

    INSERT INTO __CANONICAL_SCHEMA__.search_index(
        entity_type,
        entity_id,
        name,
        locality,
        country,
        treatments,
        specialties,
        tags
    )
    SELECT
        'document',
        d.id,
        d.title,
        '',
        '',
        COALESCE(d.raw_text, ''),
        COALESCE(d.document_type, ''),
        COALESCE((
            SELECT string_agg(DISTINCT tg.facet || ':' || tg.value, ' ' ORDER BY tg.facet || ':' || tg.value)
            FROM __CANONICAL_SCHEMA__.entity_tags et
            JOIN __CANONICAL_SCHEMA__.tags tg ON tg.id = et.tag_id
            WHERE et.entity_type = 'document'
              AND et.entity_id = d.id
        ), '')
    FROM __CANONICAL_SCHEMA__.documents d
    WHERE d.id = p_document_id
    ON CONFLICT (entity_type, entity_id) DO UPDATE SET
        name = EXCLUDED.name,
        locality = EXCLUDED.locality,
        country = EXCLUDED.country,
        treatments = EXCLUDED.treatments,
        specialties = EXCLUDED.specialties,
        tags = EXCLUDED.tags;
END;
$$;

CREATE OR REPLACE FUNCTION __CANONICAL_SCHEMA__.refresh_search_index()
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
    entity RECORD;
BEGIN
    DELETE FROM __CANONICAL_SCHEMA__.search_index;

    FOR entity IN SELECT id FROM __CANONICAL_SCHEMA__.locations ORDER BY id LOOP
        PERFORM __CANONICAL_SCHEMA__.refresh_search_index_for_location(entity.id);
    END LOOP;

    FOR entity IN SELECT id FROM __CANONICAL_SCHEMA__.practitioners ORDER BY id LOOP
        PERFORM __CANONICAL_SCHEMA__.refresh_search_index_for_practitioner(entity.id);
    END LOOP;

    FOR entity IN SELECT id FROM __CANONICAL_SCHEMA__.documents ORDER BY id LOOP
        PERFORM __CANONICAL_SCHEMA__.refresh_search_index_for_document(entity.id);
    END LOOP;
END;
$$;

CREATE OR REPLACE FUNCTION __CANONICAL_SCHEMA__.refresh_location_search_index_trigger()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    affected_practitioner_id INTEGER;
BEGIN
    IF TG_OP = 'DELETE' THEN
        DELETE FROM __CANONICAL_SCHEMA__.search_index
        WHERE entity_type = 'location'
          AND entity_id = OLD.id;

        FOR affected_practitioner_id IN
            SELECT practitioner_id
            FROM __CANONICAL_SCHEMA__.affiliations
            WHERE location_id = OLD.id
        LOOP
            PERFORM __CANONICAL_SCHEMA__.refresh_search_index_for_practitioner(affected_practitioner_id);
        END LOOP;

        RETURN OLD;
    END IF;

    PERFORM __CANONICAL_SCHEMA__.refresh_search_index_for_location(NEW.id);

    FOR affected_practitioner_id IN
        SELECT practitioner_id
        FROM __CANONICAL_SCHEMA__.affiliations
        WHERE location_id = NEW.id
    LOOP
        PERFORM __CANONICAL_SCHEMA__.refresh_search_index_for_practitioner(affected_practitioner_id);
    END LOOP;

    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION __CANONICAL_SCHEMA__.refresh_practitioner_search_index_trigger()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        DELETE FROM __CANONICAL_SCHEMA__.search_index
        WHERE entity_type = 'practitioner'
          AND entity_id = OLD.id;
        RETURN OLD;
    END IF;

    PERFORM __CANONICAL_SCHEMA__.refresh_search_index_for_practitioner(NEW.id);
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION __CANONICAL_SCHEMA__.refresh_document_search_index_trigger()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        DELETE FROM __CANONICAL_SCHEMA__.search_index
        WHERE entity_type = 'document'
          AND entity_id = OLD.id;
        RETURN OLD;
    END IF;

    PERFORM __CANONICAL_SCHEMA__.refresh_search_index_for_document(NEW.id);
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION __CANONICAL_SCHEMA__.refresh_offering_search_index_trigger()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP IN ('UPDATE', 'DELETE') THEN
        PERFORM __CANONICAL_SCHEMA__.refresh_search_index_for_location(OLD.location_id);
    END IF;

    IF TG_OP IN ('INSERT', 'UPDATE') AND (TG_OP <> 'UPDATE' OR NEW.location_id IS DISTINCT FROM OLD.location_id) THEN
        PERFORM __CANONICAL_SCHEMA__.refresh_search_index_for_location(NEW.location_id);
    END IF;

    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION __CANONICAL_SCHEMA__.refresh_affiliation_search_index_trigger()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP IN ('UPDATE', 'DELETE') THEN
        PERFORM __CANONICAL_SCHEMA__.refresh_search_index_for_practitioner(OLD.practitioner_id);
    END IF;

    IF TG_OP IN ('INSERT', 'UPDATE') AND (TG_OP <> 'UPDATE' OR NEW.practitioner_id IS DISTINCT FROM OLD.practitioner_id) THEN
        PERFORM __CANONICAL_SCHEMA__.refresh_search_index_for_practitioner(NEW.practitioner_id);
    END IF;

    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION __CANONICAL_SCHEMA__.refresh_entity_tag_search_index_trigger()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP IN ('UPDATE', 'DELETE') THEN
        IF OLD.entity_type = 'location' THEN
            PERFORM __CANONICAL_SCHEMA__.refresh_search_index_for_location(OLD.entity_id);
        ELSIF OLD.entity_type = 'practitioner' THEN
            PERFORM __CANONICAL_SCHEMA__.refresh_search_index_for_practitioner(OLD.entity_id);
        ELSIF OLD.entity_type = 'document' THEN
            PERFORM __CANONICAL_SCHEMA__.refresh_search_index_for_document(OLD.entity_id);
        END IF;
    END IF;

    IF TG_OP IN ('INSERT', 'UPDATE') THEN
        IF NEW.entity_type = 'location' THEN
            PERFORM __CANONICAL_SCHEMA__.refresh_search_index_for_location(NEW.entity_id);
        ELSIF NEW.entity_type = 'practitioner' THEN
            PERFORM __CANONICAL_SCHEMA__.refresh_search_index_for_practitioner(NEW.entity_id);
        ELSIF NEW.entity_type = 'document' THEN
            PERFORM __CANONICAL_SCHEMA__.refresh_search_index_for_document(NEW.entity_id);
        END IF;
    END IF;

    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION __CANONICAL_SCHEMA__.refresh_treatment_search_index_trigger()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    affected_location_id INTEGER;
BEGIN
    FOR affected_location_id IN
        SELECT DISTINCT location_id
        FROM __CANONICAL_SCHEMA__.offerings
        WHERE treatment_id = CASE WHEN TG_OP = 'DELETE' THEN OLD.id ELSE NEW.id END
    LOOP
        PERFORM __CANONICAL_SCHEMA__.refresh_search_index_for_location(affected_location_id);
    END LOOP;

    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;
    RETURN NEW;
END;
$$;

DO $$
DECLARE
    schema_name TEXT := '__CANONICAL_SCHEMA__';
BEGIN
    EXECUTE format('DROP TRIGGER IF EXISTS trg_refresh_location_search_index ON %I.locations', schema_name);
    EXECUTE format('CREATE TRIGGER trg_refresh_location_search_index AFTER INSERT OR UPDATE OR DELETE ON %I.locations FOR EACH ROW EXECUTE FUNCTION %I.refresh_location_search_index_trigger()', schema_name, schema_name);

    EXECUTE format('DROP TRIGGER IF EXISTS trg_refresh_practitioner_search_index ON %I.practitioners', schema_name);
    EXECUTE format('CREATE TRIGGER trg_refresh_practitioner_search_index AFTER INSERT OR UPDATE OR DELETE ON %I.practitioners FOR EACH ROW EXECUTE FUNCTION %I.refresh_practitioner_search_index_trigger()', schema_name, schema_name);

    EXECUTE format('DROP TRIGGER IF EXISTS trg_refresh_document_search_index ON %I.documents', schema_name);
    EXECUTE format('CREATE TRIGGER trg_refresh_document_search_index AFTER INSERT OR UPDATE OR DELETE ON %I.documents FOR EACH ROW EXECUTE FUNCTION %I.refresh_document_search_index_trigger()', schema_name, schema_name);

    EXECUTE format('DROP TRIGGER IF EXISTS trg_refresh_offering_search_index ON %I.offerings', schema_name);
    EXECUTE format('CREATE TRIGGER trg_refresh_offering_search_index AFTER INSERT OR UPDATE OR DELETE ON %I.offerings FOR EACH ROW EXECUTE FUNCTION %I.refresh_offering_search_index_trigger()', schema_name, schema_name);

    EXECUTE format('DROP TRIGGER IF EXISTS trg_refresh_affiliation_search_index ON %I.affiliations', schema_name);
    EXECUTE format('CREATE TRIGGER trg_refresh_affiliation_search_index AFTER INSERT OR UPDATE OR DELETE ON %I.affiliations FOR EACH ROW EXECUTE FUNCTION %I.refresh_affiliation_search_index_trigger()', schema_name, schema_name);

    EXECUTE format('DROP TRIGGER IF EXISTS trg_refresh_entity_tag_search_index ON %I.entity_tags', schema_name);
    EXECUTE format('CREATE TRIGGER trg_refresh_entity_tag_search_index AFTER INSERT OR UPDATE OR DELETE ON %I.entity_tags FOR EACH ROW EXECUTE FUNCTION %I.refresh_entity_tag_search_index_trigger()', schema_name, schema_name);

    EXECUTE format('DROP TRIGGER IF EXISTS trg_refresh_treatment_search_index ON %I.treatments', schema_name);
    EXECUTE format('CREATE TRIGGER trg_refresh_treatment_search_index AFTER UPDATE OR DELETE ON %I.treatments FOR EACH ROW EXECUTE FUNCTION %I.refresh_treatment_search_index_trigger()', schema_name, schema_name);
END $$;

CREATE OR REPLACE FUNCTION __CANONICAL_SCHEMA__.set_mutation_actor(p_actor_id UUID, p_actor_type TEXT DEFAULT 'admin')
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
    IF p_actor_id IS NOT NULL THEN
        PERFORM set_config('fountain.actor_id', p_actor_id::text, true);
    END IF;
    PERFORM set_config('fountain.actor_type', COALESCE(NULLIF(p_actor_type, ''), 'admin'), true);
END;
$$;

CREATE OR REPLACE FUNCTION __CANONICAL_SCHEMA__.create_location(p_location JSONB, p_actor_id UUID DEFAULT NULL)
RETURNS INTEGER
LANGUAGE plpgsql
AS $$
DECLARE
    new_location_id INTEGER;
BEGIN
    PERFORM __CANONICAL_SCHEMA__.set_mutation_actor(p_actor_id, 'admin');

    INSERT INTO __CANONICAL_SCHEMA__.locations(
        org_id,
        name,
        address,
        locality,
        region,
        postal_code,
        country_code,
        country_name,
        latitude,
        longitude,
        phone,
        email,
        website,
        price_text,
        rating,
        review_count,
        dedup_key,
        data_origin,
        owner_account_id,
        verification_status
    )
    VALUES (
        NULLIF(p_location->>'org_id', '')::integer,
        NULLIF(p_location->>'name', ''),
        NULLIF(p_location->>'address', ''),
        NULLIF(p_location->>'locality', ''),
        NULLIF(p_location->>'region', ''),
        NULLIF(p_location->>'postal_code', ''),
        NULLIF(p_location->>'country_code', ''),
        NULLIF(p_location->>'country_name', ''),
        NULLIF(p_location->>'latitude', '')::double precision,
        NULLIF(p_location->>'longitude', '')::double precision,
        NULLIF(p_location->>'phone', ''),
        NULLIF(p_location->>'email', ''),
        NULLIF(p_location->>'website', ''),
        NULLIF(p_location->>'price_text', ''),
        NULLIF(p_location->>'rating', '')::double precision,
        NULLIF(p_location->>'review_count', '')::integer,
        NULLIF(p_location->>'dedup_key', ''),
        COALESCE(NULLIF(p_location->>'data_origin', ''), 'manual'),
        NULLIF(p_location->>'owner_account_id', '')::uuid,
        COALESCE(NULLIF(p_location->>'verification_status', ''), 'unverified')
    )
    RETURNING id INTO new_location_id;

    RETURN new_location_id;
END;
$$;

CREATE OR REPLACE FUNCTION __CANONICAL_SCHEMA__.delete_location_cascade(
    p_location_id INTEGER,
    p_actor_id UUID DEFAULT NULL,
    p_reason TEXT DEFAULT NULL
)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
    affected_practitioner_id INTEGER;
BEGIN
    IF NOT EXISTS (SELECT 1 FROM __CANONICAL_SCHEMA__.locations WHERE id = p_location_id) THEN
        RAISE EXCEPTION 'Location % does not exist', p_location_id;
    END IF;

    PERFORM __CANONICAL_SCHEMA__.set_mutation_actor(p_actor_id, 'admin');

    CREATE TEMP TABLE IF NOT EXISTS fountain_affected_practitioners(
        practitioner_id INTEGER PRIMARY KEY
    ) ON COMMIT DROP;
    TRUNCATE fountain_affected_practitioners;

    INSERT INTO fountain_affected_practitioners(practitioner_id)
    SELECT DISTINCT practitioner_id
    FROM __CANONICAL_SCHEMA__.affiliations
    WHERE location_id = p_location_id
    ON CONFLICT DO NOTHING;

    DELETE FROM __CANONICAL_SCHEMA__.search_index
    WHERE entity_type = 'location'
      AND entity_id = p_location_id;

    DELETE FROM __CANONICAL_SCHEMA__.images
    WHERE entity_type = 'location'
      AND entity_id = p_location_id;

    DELETE FROM __CANONICAL_SCHEMA__.entity_tags
    WHERE entity_type = 'location'
      AND entity_id = p_location_id;

    DELETE FROM __CANONICAL_SCHEMA__.source_records
    WHERE entity_type = 'location'
      AND entity_id = p_location_id;

    DELETE FROM __CANONICAL_SCHEMA__.external_reviews
    WHERE location_id = p_location_id;

    DELETE FROM __CANONICAL_SCHEMA__.external_place_matches
    WHERE location_id = p_location_id;

    DELETE FROM __CANONICAL_SCHEMA__.reviews
    WHERE location_id = p_location_id;

    DELETE FROM __CANONICAL_SCHEMA__.offerings
    WHERE location_id = p_location_id;

    DELETE FROM __CANONICAL_SCHEMA__.affiliations
    WHERE location_id = p_location_id;

    DELETE FROM __CANONICAL_SCHEMA__.locations
    WHERE id = p_location_id;

    INSERT INTO __CANONICAL_SCHEMA__.entity_change_events(entity_type, entity_id, action, actor_type, actor_id, reason)
    VALUES ('location', p_location_id, 'delete_location_cascade', 'admin', p_actor_id, p_reason);

    FOR affected_practitioner_id IN SELECT practitioner_id FROM fountain_affected_practitioners LOOP
        PERFORM __CANONICAL_SCHEMA__.refresh_search_index_for_practitioner(affected_practitioner_id);
    END LOOP;
END;
$$;

CREATE OR REPLACE FUNCTION __CANONICAL_SCHEMA__.merge_locations(
    p_keep_location_id INTEGER,
    p_delete_location_id INTEGER,
    p_actor_id UUID DEFAULT NULL,
    p_reason TEXT DEFAULT NULL
)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
    affected_practitioner_id INTEGER;
BEGIN
    IF p_keep_location_id = p_delete_location_id THEN
        RAISE EXCEPTION 'Cannot merge location % into itself', p_keep_location_id;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM __CANONICAL_SCHEMA__.locations WHERE id = p_keep_location_id) THEN
        RAISE EXCEPTION 'Keep location % does not exist', p_keep_location_id;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM __CANONICAL_SCHEMA__.locations WHERE id = p_delete_location_id) THEN
        RAISE EXCEPTION 'Delete location % does not exist', p_delete_location_id;
    END IF;

    PERFORM __CANONICAL_SCHEMA__.set_mutation_actor(p_actor_id, 'admin');

    CREATE TEMP TABLE IF NOT EXISTS fountain_affected_practitioners(
        practitioner_id INTEGER PRIMARY KEY
    ) ON COMMIT DROP;
    TRUNCATE fountain_affected_practitioners;

    INSERT INTO fountain_affected_practitioners(practitioner_id)
    SELECT DISTINCT practitioner_id
    FROM __CANONICAL_SCHEMA__.affiliations
    WHERE location_id IN (p_keep_location_id, p_delete_location_id)
    ON CONFLICT DO NOTHING;

    UPDATE __CANONICAL_SCHEMA__.locations keep_location
    SET
        org_id = COALESCE(keep_location.org_id, delete_location.org_id),
        name = COALESCE(NULLIF(keep_location.name, ''), delete_location.name),
        address = COALESCE(NULLIF(keep_location.address, ''), delete_location.address),
        locality = COALESCE(NULLIF(keep_location.locality, ''), delete_location.locality),
        region = COALESCE(NULLIF(keep_location.region, ''), delete_location.region),
        postal_code = COALESCE(NULLIF(keep_location.postal_code, ''), delete_location.postal_code),
        country_code = COALESCE(NULLIF(keep_location.country_code, ''), delete_location.country_code),
        country_name = COALESCE(NULLIF(keep_location.country_name, ''), delete_location.country_name),
        latitude = COALESCE(keep_location.latitude, delete_location.latitude),
        longitude = COALESCE(keep_location.longitude, delete_location.longitude),
        phone = COALESCE(NULLIF(keep_location.phone, ''), delete_location.phone),
        email = COALESCE(NULLIF(keep_location.email, ''), delete_location.email),
        website = COALESCE(NULLIF(keep_location.website, ''), delete_location.website),
        price_text = COALESCE(NULLIF(keep_location.price_text, ''), delete_location.price_text),
        rating = COALESCE(keep_location.rating, delete_location.rating),
        review_count = GREATEST(COALESCE(keep_location.review_count, 0), COALESCE(delete_location.review_count, 0)),
        verification_status = CASE
            WHEN keep_location.verification_status = 'unverified' THEN delete_location.verification_status
            ELSE keep_location.verification_status
        END
    FROM __CANONICAL_SCHEMA__.locations delete_location
    WHERE keep_location.id = p_keep_location_id
      AND delete_location.id = p_delete_location_id;

    DELETE FROM __CANONICAL_SCHEMA__.offerings loser
    USING __CANONICAL_SCHEMA__.offerings winner
    WHERE loser.location_id = p_delete_location_id
      AND winner.location_id = p_keep_location_id
      AND winner.source_id IS NOT DISTINCT FROM loser.source_id
      AND COALESCE(winner.raw_name, '') = COALESCE(loser.raw_name, '');

    UPDATE __CANONICAL_SCHEMA__.offerings
    SET location_id = p_keep_location_id
    WHERE location_id = p_delete_location_id;

    INSERT INTO __CANONICAL_SCHEMA__.entity_tags(entity_type, entity_id, tag_id)
    SELECT entity_type, p_keep_location_id, tag_id
    FROM __CANONICAL_SCHEMA__.entity_tags
    WHERE entity_type = 'location'
      AND entity_id = p_delete_location_id
    ON CONFLICT DO NOTHING;

    DELETE FROM __CANONICAL_SCHEMA__.entity_tags
    WHERE entity_type = 'location'
      AND entity_id = p_delete_location_id;

    DELETE FROM __CANONICAL_SCHEMA__.images loser
    USING __CANONICAL_SCHEMA__.images winner
    WHERE loser.entity_type = 'location'
      AND loser.entity_id = p_delete_location_id
      AND winner.entity_type = 'location'
      AND winner.entity_id = p_keep_location_id
      AND winner.blob_url = loser.blob_url;

    UPDATE __CANONICAL_SCHEMA__.images
    SET entity_id = p_keep_location_id
    WHERE entity_type = 'location'
      AND entity_id = p_delete_location_id;

    UPDATE __CANONICAL_SCHEMA__.source_records
    SET entity_id = p_keep_location_id
    WHERE entity_type = 'location'
      AND entity_id = p_delete_location_id;

    UPDATE __CANONICAL_SCHEMA__.reviews
    SET location_id = p_keep_location_id
    WHERE location_id = p_delete_location_id;

    DELETE FROM __CANONICAL_SCHEMA__.external_place_matches loser
    USING __CANONICAL_SCHEMA__.external_place_matches winner
    WHERE loser.location_id = p_delete_location_id
      AND winner.location_id = p_keep_location_id
      AND winner.provider = loser.provider;

    UPDATE __CANONICAL_SCHEMA__.external_place_matches
    SET location_id = p_keep_location_id
    WHERE location_id = p_delete_location_id;

    UPDATE __CANONICAL_SCHEMA__.external_reviews
    SET location_id = p_keep_location_id
    WHERE location_id = p_delete_location_id;

    DELETE FROM __CANONICAL_SCHEMA__.affiliations loser
    USING __CANONICAL_SCHEMA__.affiliations winner
    WHERE loser.location_id = p_delete_location_id
      AND winner.location_id = p_keep_location_id
      AND winner.practitioner_id = loser.practitioner_id
      AND winner.org_id IS NOT DISTINCT FROM loser.org_id;

    UPDATE __CANONICAL_SCHEMA__.affiliations
    SET location_id = p_keep_location_id
    WHERE location_id = p_delete_location_id;

    UPDATE __CANONICAL_SCHEMA__.clinic_claims
    SET location_id = p_keep_location_id
    WHERE location_id = p_delete_location_id;

    UPDATE __CANONICAL_SCHEMA__.listing_submissions
    SET target_entity_id = p_keep_location_id
    WHERE target_entity_type = 'location'
      AND target_entity_id = p_delete_location_id;

    DELETE FROM __CANONICAL_SCHEMA__.search_index
    WHERE entity_type = 'location'
      AND entity_id = p_delete_location_id;

    DELETE FROM __CANONICAL_SCHEMA__.locations
    WHERE id = p_delete_location_id;

    INSERT INTO __CANONICAL_SCHEMA__.entity_change_events(entity_type, entity_id, action, actor_type, actor_id, reason, metadata)
    VALUES (
        'location',
        p_keep_location_id,
        'merge_locations',
        'admin',
        p_actor_id,
        p_reason,
        jsonb_build_object('deleted_location_id', p_delete_location_id)
    );

    PERFORM __CANONICAL_SCHEMA__.refresh_search_index_for_location(p_keep_location_id);

    FOR affected_practitioner_id IN SELECT practitioner_id FROM fountain_affected_practitioners LOOP
        PERFORM __CANONICAL_SCHEMA__.refresh_search_index_for_practitioner(affected_practitioner_id);
    END LOOP;
END;
$$;

CREATE OR REPLACE FUNCTION __CANONICAL_SCHEMA__.replace_location_offerings(
    p_location_id INTEGER,
    p_offerings JSONB,
    p_actor_id UUID DEFAULT NULL
)
RETURNS INTEGER
LANGUAGE plpgsql
AS $$
DECLARE
    inserted_count INTEGER;
BEGIN
    IF jsonb_typeof(p_offerings) <> 'array' THEN
        RAISE EXCEPTION 'p_offerings must be a JSON array';
    END IF;

    IF NOT EXISTS (SELECT 1 FROM __CANONICAL_SCHEMA__.locations WHERE id = p_location_id) THEN
        RAISE EXCEPTION 'Location % does not exist', p_location_id;
    END IF;

    PERFORM __CANONICAL_SCHEMA__.set_mutation_actor(p_actor_id, 'admin');

    DELETE FROM __CANONICAL_SCHEMA__.offerings
    WHERE location_id = p_location_id;

    INSERT INTO __CANONICAL_SCHEMA__.offerings(
        location_id,
        treatment_id,
        raw_name,
        price_amount,
        price_currency,
        source_offer_url,
        source_id,
        data_origin,
        verification_status
    )
    SELECT
        p_location_id,
        treatment_id,
        raw_name,
        price_amount,
        price_currency,
        source_offer_url,
        source_id,
        'manual',
        'unverified'
    FROM jsonb_to_recordset(p_offerings) AS offering(
        treatment_id INTEGER,
        raw_name TEXT,
        price_amount DOUBLE PRECISION,
        price_currency TEXT,
        source_offer_url TEXT,
        source_id INTEGER
    )
    WHERE COALESCE(raw_name, '') <> '';

    GET DIAGNOSTICS inserted_count = ROW_COUNT;
    PERFORM __CANONICAL_SCHEMA__.refresh_search_index_for_location(p_location_id);
    RETURN inserted_count;
END;
$$;

CREATE OR REPLACE FUNCTION __CANONICAL_SCHEMA__.attach_location_image(
    p_location_id INTEGER,
    p_blob_url TEXT,
    p_image_url TEXT DEFAULT NULL,
    p_alt TEXT DEFAULT NULL,
    p_source_id INTEGER DEFAULT NULL,
    p_actor_id UUID DEFAULT NULL
)
RETURNS INTEGER
LANGUAGE plpgsql
AS $$
DECLARE
    new_image_id INTEGER;
BEGIN
    IF COALESCE(p_blob_url, '') = '' THEN
        RAISE EXCEPTION 'p_blob_url is required';
    END IF;

    IF NOT EXISTS (SELECT 1 FROM __CANONICAL_SCHEMA__.locations WHERE id = p_location_id) THEN
        RAISE EXCEPTION 'Location % does not exist', p_location_id;
    END IF;

    PERFORM __CANONICAL_SCHEMA__.set_mutation_actor(p_actor_id, 'admin');

    INSERT INTO __CANONICAL_SCHEMA__.images(
        entity_type,
        entity_id,
        image_url,
        local_path,
        blob_url,
        alt,
        source_id,
        data_origin,
        verification_status
    )
    VALUES (
        'location',
        p_location_id,
        p_image_url,
        NULL,
        p_blob_url,
        p_alt,
        p_source_id,
        'manual',
        'unverified'
    )
    RETURNING id INTO new_image_id;

    RETURN new_image_id;
END;
$$;
