-- Introduce optional treatment families and specific searchable leaves.
-- Raw clinic menu names remain untouched. Customer synonyms are curated and
-- separate from ingestion aliases. Retire the unused presentation/provenance
-- metadata that previously encouraged broad duplicate suppression.

BEGIN;

SELECT fountain.set_mutation_actor(
  'b5c71897-83d0-4c30-a7a3-202608120001'::uuid,
  'specific_treatment_hierarchy_and_search_20260812'
);

CREATE TABLE IF NOT EXISTS fountain_raw.treatment_term_presentations_retired_20260812 AS
SELECT presentation.*, now() AS retired_at
FROM fountain.treatment_term_presentations presentation;

CREATE TABLE IF NOT EXISTS fountain_raw.source_offering_granularity_retired_20260812 AS
SELECT source.id, source.slug, source.offering_granularity, now() AS retired_at
FROM fountain.sources source;

CREATE TABLE IF NOT EXISTS fountain_raw.legacy_summary_suppressions_retired_20260812 AS
SELECT suppression.*, now() AS retired_at
FROM fountain.offering_display_suppressions suppression
WHERE suppression.active
  AND suppression.reason = 'legacy_summary_shadow'
  AND suppression.rule_version LIKE 'offering-display-%';

CREATE TABLE IF NOT EXISTS fountain_raw.treatments_before_specific_hierarchy_20260812 AS
SELECT treatment.*, now() AS backed_up_at
FROM fountain.treatments treatment;

ALTER TABLE fountain.treatments
  ADD COLUMN IF NOT EXISTS parent_treatment_id integer;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'fountain.treatments'::regclass
      AND conname = 'treatments_parent_treatment_id_fkey'
  ) THEN
    ALTER TABLE fountain.treatments
      ADD CONSTRAINT treatments_parent_treatment_id_fkey
      FOREIGN KEY (parent_treatment_id)
      REFERENCES fountain.treatments(id)
      ON DELETE SET NULL;
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'fountain.treatments'::regclass
      AND conname = 'treatments_parent_not_self'
  ) THEN
    ALTER TABLE fountain.treatments
      ADD CONSTRAINT treatments_parent_not_self
      CHECK (parent_treatment_id IS NULL OR parent_treatment_id <> id);
  END IF;
END;
$$;

CREATE INDEX IF NOT EXISTS treatments_parent_treatment_id_idx
  ON fountain.treatments(parent_treatment_id);

CREATE OR REPLACE FUNCTION fountain.treatment_descendants(p_treatment_id integer)
RETURNS TABLE(id integer)
LANGUAGE sql
STABLE
PARALLEL SAFE
AS $$
  WITH RECURSIVE treatment_tree(id, visited) AS (
    SELECT treatment.id, ARRAY[treatment.id]
    FROM fountain.treatments treatment
    WHERE treatment.id = p_treatment_id
    UNION ALL
    SELECT child.id, treatment_tree.visited || child.id
    FROM fountain.treatments child
    JOIN treatment_tree ON child.parent_treatment_id = treatment_tree.id
    WHERE NOT child.id = ANY(treatment_tree.visited)
  )
  SELECT treatment_tree.id FROM treatment_tree
$$;

COMMENT ON COLUMN fountain.treatments.parent_treatment_id IS
  'Optional search hierarchy. Specific leaf searches remain exact; family searches include descendants.';

CREATE TABLE IF NOT EXISTS fountain.treatment_synonyms (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  treatment_id integer NOT NULL REFERENCES fountain.treatments(id) ON DELETE CASCADE,
  synonym text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT treatment_synonyms_nonempty CHECK (btrim(synonym) <> '')
);

CREATE UNIQUE INDEX IF NOT EXISTS treatment_synonyms_text_unique
  ON fountain.treatment_synonyms(lower(btrim(synonym)));
CREATE INDEX IF NOT EXISTS treatment_synonyms_treatment_idx
  ON fountain.treatment_synonyms(treatment_id);

COMMENT ON TABLE fountain.treatment_synonyms IS
  'Human-curated semantic equivalents for customer search. Formatting variants are normalized in code.';

CREATE TEMP TABLE desired_treatments (
  canonical_name text PRIMARY KEY,
  category text NOT NULL,
  parent_name text,
  description text NOT NULL
) ON COMMIT DROP;

INSERT INTO desired_treatments (canonical_name, category, parent_name, description)
VALUES
  ('Imaging', 'Measure', NULL, 'Medical imaging family spanning MRI, CT, DEXA, X-ray, ultrasound, and related modalities.'),
  ('Neuromodulator injections', 'Rejuvenate', NULL, 'Injectable neuromodulator family including distinct botulinum toxin products.'),
  ('Whole-body MRI', 'Measure', 'MRI', 'Magnetic resonance imaging intended to scan most or all of the body.'),
  ('BPC-157', 'Regenerate', 'Peptide therapy', 'Treatment specifically using the peptide BPC-157.'),
  ('MOTS-C', 'Regenerate', 'Peptide therapy', 'Treatment specifically using the mitochondrial-derived peptide MOTS-C.'),
  ('Sermorelin', 'Regenerate', 'Peptide therapy', 'Treatment specifically using sermorelin.'),
  ('Tesamorelin', 'Regenerate', 'Peptide therapy', 'Treatment specifically using tesamorelin.'),
  ('PT-141', 'Regenerate', 'Peptide therapy', 'Treatment specifically using PT-141 (bremelanotide).'),
  ('GHK-Cu', 'Regenerate', 'Peptide therapy', 'Treatment specifically using the copper peptide GHK-Cu.'),
  ('AOD-9604', 'Regenerate', 'Peptide therapy', 'Treatment specifically using AOD-9604.'),
  ('TB-500', 'Regenerate', 'Peptide therapy', 'Treatment specifically using TB-500.'),
  ('Thymosin alpha-1', 'Regenerate', 'Peptide therapy', 'Treatment specifically using thymosin alpha-1.'),
  ('Semax', 'Regenerate', 'Peptide therapy', 'Treatment specifically using Semax.'),
  ('Selank', 'Regenerate', 'Peptide therapy', 'Treatment specifically using Selank.'),
  ('Ipamorelin', 'Regenerate', 'Peptide therapy', 'Treatment specifically using ipamorelin.'),
  ('CJC-1295', 'Regenerate', 'Peptide therapy', 'Treatment specifically using CJC-1295.'),
  ('CJC-1295 + Ipamorelin', 'Regenerate', 'Peptide therapy', 'Combination treatment specifically using CJC-1295 and ipamorelin.'),
  ('KPV', 'Regenerate', 'Peptide therapy', 'Treatment specifically using KPV.'),
  ('DSIP', 'Regenerate', 'Peptide therapy', 'Treatment specifically using delta sleep-inducing peptide (DSIP).'),
  ('Epitalon', 'Regenerate', 'Peptide therapy', 'Treatment specifically using Epitalon.'),
  ('Kisspeptin-10', 'Regenerate', 'Peptide therapy', 'Treatment specifically using Kisspeptin-10.'),
  ('Melanotan II', 'Regenerate', 'Peptide therapy', 'Treatment specifically using Melanotan II.'),
  ('Dihexa', 'Regenerate', 'Peptide therapy', 'Treatment specifically using Dihexa.'),
  ('Myers'' Cocktail IV', 'Optimize', 'IV Infusions', 'IV infusion specifically described as a Myers'' Cocktail.'),
  ('Vitamin C IV', 'Optimize', 'IV Infusions', 'IV infusion specifically centered on vitamin C.'),
  ('Glutathione IV', 'Optimize', 'IV Infusions', 'IV infusion specifically centered on glutathione.'),
  ('Alpha-lipoic acid IV', 'Optimize', 'IV Infusions', 'IV infusion specifically centered on alpha-lipoic acid.'),
  ('Iron infusion', 'Optimize', 'IV Infusions', 'Intravenous iron infusion.'),
  ('IV hydration', 'Optimize', 'IV Infusions', 'IV fluid treatment specifically centered on hydration.'),
  ('B-complex IV', 'Optimize', 'IV Infusions', 'IV infusion specifically centered on B-complex vitamins.'),
  ('Magnesium IV', 'Optimize', 'IV Infusions', 'IV infusion specifically centered on magnesium.'),
  ('Dysport', 'Rejuvenate', 'Neuromodulator injections', 'Treatment specifically using Dysport.'),
  ('Xeomin', 'Rejuvenate', 'Neuromodulator injections', 'Treatment specifically using Xeomin.'),
  ('Jeuveau', 'Rejuvenate', 'Neuromodulator injections', 'Treatment specifically using Jeuveau.'),
  ('Daxxify', 'Rejuvenate', 'Neuromodulator injections', 'Treatment specifically using Daxxify.'),
  ('Rapamycin', 'Optimize', 'Medication management', 'Treatment or prescribing plan specifically involving rapamycin.'),
  ('Modafinil', 'Optimize', 'Medication management', 'Treatment or prescribing plan specifically involving modafinil.');

-- Insert roots first, then leaves. Existing treatments keep stable IDs.
INSERT INTO fountain.treatments (id, canonical_name, description, category)
SELECT
  nextval(pg_get_serial_sequence('fountain.treatments', 'id'))::integer,
  desired.canonical_name,
  desired.description,
  desired.category
FROM desired_treatments desired
WHERE desired.parent_name IS NULL
ON CONFLICT (canonical_name) DO UPDATE
SET description = EXCLUDED.description,
    category = EXCLUDED.category;

INSERT INTO fountain.treatments (id, canonical_name, description, category, parent_treatment_id)
SELECT
  nextval(pg_get_serial_sequence('fountain.treatments', 'id'))::integer,
  desired.canonical_name,
  desired.description,
  desired.category,
  parent.id
FROM desired_treatments desired
JOIN fountain.treatments parent ON parent.canonical_name = desired.parent_name
WHERE desired.parent_name IS NOT NULL
ON CONFLICT (canonical_name) DO UPDATE
SET description = EXCLUDED.description,
    category = EXCLUDED.category,
    parent_treatment_id = EXCLUDED.parent_treatment_id;

-- Only the families discussed here get parents. The hierarchy remains optional.
UPDATE fountain.treatments child
SET parent_treatment_id = parent.id
FROM fountain.treatments parent
WHERE parent.canonical_name = 'Imaging'
  AND child.canonical_name IN (
    'MRI', 'CT', 'DEXA scan', 'X-ray', 'Diagnostic imaging', 'Fluoroscopy',
    'Mammography', 'Nuclear medicine imaging', 'PET scan', 'Ultrasound imaging',
    'Vascular imaging'
  );

UPDATE fountain.treatments child
SET parent_treatment_id = parent.id
FROM fountain.treatments parent
WHERE parent.canonical_name = 'IV Infusions'
  AND child.canonical_name = 'NAD+ IV therapy';

UPDATE fountain.treatments child
SET parent_treatment_id = parent.id
FROM fountain.treatments parent
WHERE parent.canonical_name = 'Neuromodulator injections'
  AND child.canonical_name = 'Botox';

CREATE TEMP TABLE curated_synonyms (
  canonical_name text NOT NULL,
  synonym text NOT NULL,
  PRIMARY KEY (canonical_name, synonym)
) ON COMMIT DROP;

INSERT INTO curated_synonyms (canonical_name, synonym)
VALUES
  ('Whole-body MRI', 'Full-body MRI'),
  ('Whole-body MRI', 'Entire-body MRI'),
  ('Myers'' Cocktail IV', 'Myers Cocktail'),
  ('Myers'' Cocktail IV', 'Myers IV'),
  ('Myers'' Cocktail IV', 'Myers Drip'),
  ('Alpha-lipoic acid IV', 'Alpha Lipoic Acid IV'),
  ('Alpha-lipoic acid IV', 'ALA IV'),
  ('PT-141', 'Bremelanotide'),
  ('Botox', 'OnabotulinumtoxinA'),
  ('Dysport', 'AbobotulinumtoxinA'),
  ('Xeomin', 'IncobotulinumtoxinA'),
  ('Jeuveau', 'PrabotulinumtoxinA-xvfs'),
  ('Daxxify', 'DaxibotulinumtoxinA-lanm'),
  ('Rapamycin', 'Sirolimus');

INSERT INTO fountain.treatment_synonyms (treatment_id, synonym)
SELECT treatment.id, curated.synonym
FROM curated_synonyms curated
JOIN fountain.treatments treatment ON treatment.canonical_name = curated.canonical_name
ON CONFLICT ((lower(btrim(synonym)))) DO UPDATE
SET treatment_id = EXCLUDED.treatment_id,
    synonym = EXCLUDED.synonym,
    updated_at = now();

CREATE TEMP TABLE specific_treatment_rules (
  target_name text NOT NULL,
  term_pattern text NOT NULL,
  scope_treatment_name text,
  priority integer NOT NULL DEFAULT 50
) ON COMMIT DROP;

INSERT INTO specific_treatment_rules (target_name, term_pattern, scope_treatment_name, priority)
VALUES
  ('BPC-157', '(^| )bpc ?157( |$)', NULL, 50),
  ('MOTS-C', '(^| )mots ?c( |$)', NULL, 50),
  ('Sermorelin', '(^| )sermorelin( |$)', NULL, 50),
  ('Tesamorelin', '(^| )tesamorelin( |$)', NULL, 50),
  ('PT-141', '(^| )pt ?141( |$)|(^| )bremelanotide( |$)', NULL, 50),
  ('GHK-Cu', '(^| )ghk ?cu( |$)', NULL, 50),
  ('AOD-9604', '(^| )aod ?9604( |$)', NULL, 50),
  ('TB-500', '(^| )tb ?500( |$)', NULL, 50),
  ('Thymosin alpha-1', '(^| )(thymosin (alpha|a) ?1|ta ?1)( |$)', NULL, 50),
  ('Semax', '(^| )semax( |$)', NULL, 50),
  ('Selank', '(^| )selank( |$)', NULL, 50),
  ('Ipamorelin', '(^| )ipamorelin( |$)', NULL, 50),
  ('CJC-1295', '(^| )cjc ?1295( |$)', NULL, 50),
  ('CJC-1295 + Ipamorelin', 'cjc ?1295.*ipamorelin|ipamorelin.*cjc ?1295', NULL, 100),
  ('KPV', '(^| )kpv( |$)', NULL, 50),
  ('DSIP', '(^| )dsip( |$)', NULL, 50),
  ('Epitalon', '(^| )epitalon( |$)', NULL, 50),
  ('Kisspeptin-10', '(^| )kisspeptin( ?10)?( |$)', NULL, 50),
  ('Melanotan II', '(^| )melanotan( ii| 2)?( |$)', NULL, 50),
  ('Dihexa', '(^| )dihexa( |$)', NULL, 50),
  ('Myers'' Cocktail IV', '(^| )myers( |$)', NULL, 100),
  ('Vitamin C IV', '(^| )vitamin c( |$)|(^| )high dose vitamin c( |$)', 'IV Infusions', 50),
  ('Glutathione IV', '(^| )glutathione( |$)', 'IV Infusions', 50),
  ('Alpha-lipoic acid IV', '(^| )(alpha lipoic acid|ala)( |$)', 'IV Infusions', 50),
  ('Iron infusion', '(^| )iron infusion(s)?( |$)', NULL, 50),
  ('IV hydration', '(^| )(iv hydration|hydration iv|hydration drip)( |$)', NULL, 50),
  ('B-complex IV', '(^| )b complex( |$)', 'IV Infusions', 50),
  ('Magnesium IV', '(^| )magnesium( |$)', 'IV Infusions', 50),
  ('NAD+ IV therapy', '(^| )nad( |$)', NULL, 50),
  ('Botox', '(^| )botox( |$)', NULL, 50),
  ('Dysport', '(^| )dysport( |$)', NULL, 50),
  ('Xeomin', '(^| )xeomin( |$)', NULL, 50),
  ('Jeuveau', '(^| )jeuveau( |$)', NULL, 50),
  ('Daxxify', '(^| )daxxify( |$)', NULL, 50),
  ('Rapamycin', '(^| )(rapamycin|sirolimus)( |$)', NULL, 50),
  ('Modafinil', '(^| )modafinil( |$)', NULL, 50),
  ('Whole-body MRI', '(^| )(whole|full|entire) body (mri|scan)( |$)', 'MRI', 50);

CREATE TEMP TABLE normalized_offerings ON COMMIT DROP AS
SELECT source.id AS offering_id,
       source.treatment_id,
       fountain_raw.normalize_treatment_term(source.raw_name) AS term_normalized
FROM fountain.offerings source;

DELETE FROM normalized_offerings
WHERE term_normalized !~ '(^| )(bpc|mots|pt ?141|ghk|aod|tb ?500|ta ?1|cjc)'
  AND term_normalized !~ '(^| )(sermorelin|tesamorelin|bremelanotide|thymosin|semax|selank|ipamorelin|kpv|dsip|epitalon|kisspeptin|melanotan|dihexa|myers|vitamin|glutathione|alpha|ala|iron|hydration|magnesium|nad|botox|dysport|xeomin|jeuveau|daxxify|rapamycin|sirolimus|modafinil|whole|full|entire)( |$)'
  AND term_normalized !~ '(^| )(iv hydration|b complex)( |$)';

ANALYZE normalized_offerings;

CREATE TEMP TABLE offering_specific_candidates ON COMMIT DROP AS
SELECT
  offering.offering_id,
  offering.treatment_id AS previous_treatment_id,
  target.id AS target_treatment_id,
  rule.priority
FROM normalized_offerings offering
LEFT JOIN fountain.treatments current_treatment ON current_treatment.id = offering.treatment_id
JOIN specific_treatment_rules rule
  ON offering.term_normalized ~ rule.term_pattern
 AND (rule.scope_treatment_name IS NULL OR current_treatment.canonical_name = rule.scope_treatment_name)
JOIN fountain.treatments target ON target.canonical_name = rule.target_name;

CREATE TEMP TABLE offering_specific_assignments ON COMMIT DROP AS
WITH maximum_priority AS (
  SELECT offering_id, max(priority) AS priority
  FROM offering_specific_candidates
  GROUP BY offering_id
), eligible AS (
  SELECT candidate.offering_id,
         min(candidate.previous_treatment_id) AS previous_treatment_id,
         min(candidate.target_treatment_id) AS target_treatment_id
  FROM offering_specific_candidates candidate
  JOIN maximum_priority maximum
    ON maximum.offering_id = candidate.offering_id
   AND maximum.priority = candidate.priority
  GROUP BY candidate.offering_id
  HAVING count(DISTINCT candidate.target_treatment_id) = 1
)
SELECT * FROM eligible;

CREATE TEMP TABLE alias_specific_candidates ON COMMIT DROP AS
SELECT alias.id AS alias_id, target.id AS target_treatment_id, rule.priority
FROM fountain_raw.treatment_aliases alias
LEFT JOIN fountain.treatments current_treatment ON current_treatment.id = alias.treatment_id
JOIN specific_treatment_rules rule
  ON alias.alias_normalized ~ rule.term_pattern
 AND (rule.scope_treatment_name IS NULL OR current_treatment.canonical_name = rule.scope_treatment_name)
JOIN fountain.treatments target ON target.canonical_name = rule.target_name;

CREATE TEMP TABLE alias_specific_assignments ON COMMIT DROP AS
WITH maximum_priority AS (
  SELECT alias_id, max(priority) AS priority
  FROM alias_specific_candidates
  GROUP BY alias_id
)
SELECT candidate.alias_id, min(candidate.target_treatment_id) AS target_treatment_id
FROM alias_specific_candidates candidate
JOIN maximum_priority maximum
  ON maximum.alias_id = candidate.alias_id
 AND maximum.priority = candidate.priority
GROUP BY candidate.alias_id
HAVING count(DISTINCT candidate.target_treatment_id) = 1;

CREATE TEMP TABLE term_specific_candidates ON COMMIT DROP AS
SELECT classification.term_normalized, target.id AS target_treatment_id, rule.priority
FROM fountain_raw.treatment_term_classifications classification
LEFT JOIN fountain.treatments current_treatment ON current_treatment.id = classification.treatment_id
JOIN specific_treatment_rules rule
  ON classification.term_normalized ~ rule.term_pattern
 AND (rule.scope_treatment_name IS NULL OR current_treatment.canonical_name = rule.scope_treatment_name)
JOIN fountain.treatments target ON target.canonical_name = rule.target_name;

CREATE TEMP TABLE term_specific_assignments ON COMMIT DROP AS
WITH maximum_priority AS (
  SELECT term_normalized, max(priority) AS priority
  FROM term_specific_candidates
  GROUP BY term_normalized
)
SELECT candidate.term_normalized, min(candidate.target_treatment_id) AS target_treatment_id
FROM term_specific_candidates candidate
JOIN maximum_priority maximum
  ON maximum.term_normalized = candidate.term_normalized
 AND maximum.priority = candidate.priority
GROUP BY candidate.term_normalized
HAVING count(DISTINCT candidate.target_treatment_id) = 1;

CREATE TABLE IF NOT EXISTS fountain_raw.specific_treatment_offerings_backup_20260812 AS
SELECT offering.*, now() AS backed_up_at
FROM fountain.offerings offering
WHERE offering.id IN (SELECT offering_id FROM offering_specific_assignments)
   OR offering.treatment_id = (SELECT id FROM fountain.treatments WHERE canonical_name = 'Botox');

CREATE TABLE IF NOT EXISTS fountain_raw.specific_treatment_aliases_backup_20260812 AS
SELECT alias.*, now() AS backed_up_at
FROM fountain_raw.treatment_aliases alias
WHERE alias.id IN (SELECT alias_id FROM alias_specific_assignments)
   OR alias.treatment_id = (SELECT id FROM fountain.treatments WHERE canonical_name = 'Botox');

CREATE TABLE IF NOT EXISTS fountain_raw.specific_treatment_classifications_backup_20260812 AS
SELECT classification.*, now() AS backed_up_at
FROM fountain_raw.treatment_term_classifications classification
WHERE classification.term_normalized IN (SELECT term_normalized FROM term_specific_assignments)
   OR classification.treatment_id = (SELECT id FROM fountain.treatments WHERE canonical_name = 'Botox');

-- Botox historically acted as the whole family. Generic and multi-brand rows
-- move to the family; unambiguous brand rows are assigned below.
UPDATE fountain.offerings offering
SET treatment_id = family.id,
    updated_at = now()
FROM fountain.treatments botox
CROSS JOIN fountain.treatments family
WHERE botox.canonical_name = 'Botox'
  AND family.canonical_name = 'Neuromodulator injections'
  AND offering.treatment_id = botox.id;

UPDATE fountain_raw.treatment_aliases alias
SET treatment_id = family.id,
    mapping_review_model = 'human',
    mapping_reviewed_at = now(),
    mapping_review_rationale = 'Generic or multi-brand neuromodulator wording belongs to the family; exact brands use leaf treatments.'
FROM fountain.treatments botox
CROSS JOIN fountain.treatments family
WHERE botox.canonical_name = 'Botox'
  AND family.canonical_name = 'Neuromodulator injections'
  AND alias.treatment_id = botox.id;

UPDATE fountain_raw.treatment_term_classifications classification
SET treatment_id = family.id,
    broad_category = family.category,
    updated_at = now()
FROM fountain.treatments botox
CROSS JOIN fountain.treatments family
WHERE botox.canonical_name = 'Botox'
  AND family.canonical_name = 'Neuromodulator injections'
  AND classification.treatment_id = botox.id;

UPDATE fountain.offerings offering
SET treatment_id = assignment.target_treatment_id,
    updated_at = now()
FROM offering_specific_assignments assignment
WHERE offering.id = assignment.offering_id
  AND offering.treatment_id IS DISTINCT FROM assignment.target_treatment_id;

UPDATE fountain_raw.treatment_aliases alias
SET treatment_id = assignment.target_treatment_id,
    mapping_status = 'active',
    mapping_confidence = 1,
    mapping_review_model = 'human',
    mapping_reviewed_at = now(),
    mapping_review_rationale = 'Specific compound, product, modality, or named IV treatment maps to its canonical leaf.'
FROM alias_specific_assignments assignment
WHERE alias.id = assignment.alias_id;

UPDATE fountain_raw.treatment_term_classifications classification
SET treatment_id = assignment.target_treatment_id,
    broad_category = treatment.category,
    disposition = 'mapped_existing',
    confidence = 1,
    method = 'human_taxonomy_rule',
    model = NULL,
    rationale = 'Specific treatment term maps to its canonical leaf while the clinic raw name remains unchanged.',
    classified_at = now(),
    updated_at = now()
FROM term_specific_assignments assignment
JOIN fountain.treatments treatment ON treatment.id = assignment.target_treatment_id
WHERE classification.term_normalized = assignment.term_normalized;

-- Canonical leaves and curated equivalents are valid ingestion mappings too.
INSERT INTO fountain_raw.treatment_aliases (
  id, treatment_id, alias_text, alias_normalized, source_slug,
  mapping_status, mapping_confidence, mapping_review_model,
  mapping_reviewed_at, mapping_review_rationale
)
SELECT
  nextval(pg_get_serial_sequence('fountain_raw.treatment_aliases', 'id'))::integer,
  term.treatment_id,
  term.alias_text,
  term.alias_normalized,
  'specific_treatment_taxonomy_20260812',
  'active', 1, 'human', now(),
  'Approved specific canonical treatment or curated semantic equivalent.'
FROM (
  SELECT DISTINCT ON (normalized.alias_normalized)
    treatment.id AS treatment_id,
    source.alias_text,
    normalized.alias_normalized
  FROM (
    SELECT desired.canonical_name, desired.canonical_name AS alias_text
    FROM desired_treatments desired
    WHERE desired.parent_name IS NOT NULL
    UNION ALL
    SELECT curated.canonical_name, curated.synonym
    FROM curated_synonyms curated
  ) source
  JOIN fountain.treatments treatment ON treatment.canonical_name = source.canonical_name
  CROSS JOIN LATERAL (
    SELECT fountain_raw.normalize_treatment_term(source.alias_text) AS alias_normalized
  ) normalized
  WHERE normalized.alias_normalized <> ''
  ORDER BY normalized.alias_normalized, length(source.alias_text), source.alias_text
) term
ON CONFLICT (alias_normalized, source_slug) DO UPDATE
SET treatment_id = EXCLUDED.treatment_id,
    alias_text = EXCLUDED.alias_text,
    mapping_status = 'active',
    mapping_confidence = 1,
    mapping_review_model = 'human',
    mapping_reviewed_at = now(),
    mapping_review_rationale = EXCLUDED.mapping_review_rationale;

-- The old provenance values no longer control duplicate resolution. Retire
-- automatic suppressions that depended on them before dropping the column.
UPDATE fountain.offering_display_suppressions
SET active = false,
    updated_at = now(),
    evidence = evidence || jsonb_build_object(
      'retired_by', 'specific_treatment_hierarchy_and_search_20260812',
      'retired_reason', 'source provenance is not valid duplicate evidence'
    )
WHERE active
  AND reason = 'legacy_summary_shadow'
  AND rule_version LIKE 'offering-display-%';

DROP TABLE fountain.treatment_term_presentations;

ALTER TABLE fountain.sources
  DROP CONSTRAINT IF EXISTS sources_offering_granularity_valid,
  DROP COLUMN IF EXISTS offering_granularity;

DO $$
DECLARE
  bpc_id integer;
  mots_id integer;
  peptide_id integer;
  botox_id integer;
  neuromodulator_id integer;
BEGIN
  SELECT id INTO STRICT bpc_id FROM fountain.treatments WHERE canonical_name = 'BPC-157';
  SELECT id INTO STRICT mots_id FROM fountain.treatments WHERE canonical_name = 'MOTS-C';
  SELECT id INTO STRICT peptide_id FROM fountain.treatments WHERE canonical_name = 'Peptide therapy';
  SELECT id INTO STRICT botox_id FROM fountain.treatments WHERE canonical_name = 'Botox';
  SELECT id INTO STRICT neuromodulator_id FROM fountain.treatments WHERE canonical_name = 'Neuromodulator injections';

  IF (SELECT parent_treatment_id FROM fountain.treatments WHERE id = bpc_id) IS DISTINCT FROM peptide_id
     OR (SELECT parent_treatment_id FROM fountain.treatments WHERE id = mots_id) IS DISTINCT FROM peptide_id THEN
    RAISE EXCEPTION 'Peptide leaf hierarchy was not created correctly';
  END IF;

  IF (SELECT parent_treatment_id FROM fountain.treatments WHERE id = botox_id) IS DISTINCT FROM neuromodulator_id THEN
    RAISE EXCEPTION 'Botox is not under the neuromodulator family';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM offering_specific_assignments
    WHERE target_treatment_id = bpc_id
  ) OR EXISTS (
    SELECT 1
    FROM offering_specific_assignments assignment
    JOIN fountain.offerings offering ON offering.id = assignment.offering_id
    WHERE assignment.target_treatment_id = bpc_id
      AND offering.treatment_id IS DISTINCT FROM bpc_id
  ) THEN
    RAISE EXCEPTION 'An unambiguous BPC-157 offering did not map to BPC-157';
  END IF;

  IF to_regclass('fountain.treatment_term_presentations') IS NOT NULL THEN
    RAISE EXCEPTION 'Retired treatment presentation table still exists';
  END IF;

  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'fountain'
      AND table_name = 'sources'
      AND column_name = 'offering_granularity'
  ) THEN
    RAISE EXCEPTION 'Retired source offering granularity column still exists';
  END IF;

  IF EXISTS (
    WITH RECURSIVE ancestry AS (
      SELECT id AS origin_id, parent_treatment_id, ARRAY[id] AS visited
      FROM fountain.treatments
      UNION ALL
      SELECT ancestry.origin_id, parent.parent_treatment_id, ancestry.visited || parent.id
      FROM ancestry
      JOIN fountain.treatments parent ON parent.id = ancestry.parent_treatment_id
      WHERE NOT parent.id = ANY(ancestry.visited)
    )
    SELECT 1 FROM ancestry WHERE parent_treatment_id = ANY(visited)
  ) THEN
    RAISE EXCEPTION 'Treatment hierarchy contains a cycle';
  END IF;
END;
$$;

SELECT fountain.refresh_city_index();

COMMIT;
