from __future__ import annotations

from dataclasses import dataclass, field
from urllib.parse import urlparse


@dataclass(frozen=True)
class SourceConfig:
    slug: str
    name: str
    seeds: tuple[str, ...]
    listing_hints: tuple[str, ...] = ()
    follow_hints: tuple[str, ...] = ()
    exclude_hints: tuple[str, ...] = ()
    max_pages: int = 250
    max_depth: int = 3
    delay_seconds: float = 0.75
    allowed_domains: tuple[str, ...] = field(default_factory=tuple)

    def domains(self) -> set[str]:
        domains = {urlparse(seed).netloc.lower().lstrip("www.") for seed in self.seeds}
        domains.update(domain.lower().lstrip("www.") for domain in self.allowed_domains)
        return domains


TOP_US_CLASSPASS_MARKETS = (
    "new-york-metro",
    "los-angeles",
    "chicago",
    "dallas",
    "houston",
    "washington-dc",
    "philadelphia",
    "atlanta",
    "miami",
    "phoenix",
    "boston",
    "san-francisco",
    "riverside",
    "detroit",
    "seattle",
    "minneapolis",
    "san-diego",
    "tampa",
    "denver",
    "baltimore",
    "st-louis",
    "charlotte",
    "orlando",
    "san-antonio",
    "portland",
    "sacramento",
    "pittsburgh",
    "austin",
    "las-vegas",
    "cincinnati",
)


CLASSPASS_WELLNESS_CATEGORIES = ("cryotherapy", "sports-recovery")


REALSELF_CITIES = (
    ("Georgia", "Atlanta"),
    ("Texas", "Austin"),
    ("Massachusetts", "Boston"),
    ("North-Carolina", "Charlotte"),
    ("Illinois", "Chicago"),
    ("Texas", "Dallas"),
    ("Colorado", "Denver"),
    ("Michigan", "Detroit"),
    ("Texas", "Houston"),
    ("California", "Los-Angeles"),
    ("Florida", "Miami"),
    ("New-York", "New-York"),
    ("Florida", "Orlando"),
    ("Pennsylvania", "Philadelphia"),
    ("Arizona", "Phoenix"),
    ("Texas", "San-Antonio"),
    ("California", "San-Diego"),
    ("California", "San-Francisco"),
    ("Washington", "Seattle"),
)


REALSELF_PROVIDER_TYPES = (
    "Plastic-Surgeon",
    "Board-Eligible-Plastic-Surgeon",
    "Facial-Plastic-Surgeon",
    "Dermatologist",
    "Dermatologic-Surgeon",
    "Oculoplastic-Surgeon",
    "Hair-Restoration-Surgeon",
)


def _paged_urls(base_url: str, last_page: int, marker: str = "page") -> tuple[str, ...]:
    base = base_url.rstrip("/")
    return tuple([base_url] + [f"{base}/{marker}={page}/" for page in range(2, last_page + 1)])


def _path_pages(base_url: str, last_page: int, marker: str = "page") -> tuple[str, ...]:
    base = base_url.rstrip("/")
    return tuple([base_url] + [f"{base}/{marker}/{page}/" for page in range(2, last_page + 1)])


SOURCES = {
    "spannr": SourceConfig(
        slug="spannr",
        name="Spannr",
        seeds=("https://spannr.com/marketplace",),
        listing_hints=("/marketplace/clinic/", "/marketplace/retreat/"),
        follow_hints=("/marketplace", "/marketplace/clinic/", "/marketplace/retreat/"),
        exclude_hints=("/blog", "/about", "/privacy", "/terms", "/login", "/sign"),
        max_pages=350,
        max_depth=4,
    ),
    "longevity_technology_clinics": SourceConfig(
        slug="longevity_technology_clinics",
        name="Longevity Technology Clinics",
        seeds=("https://longevity.technology/clinics",),
        listing_hints=("/clinics/longevity-clinics/", "/clinics/contact?clinic_name="),
        follow_hints=("/clinics/longevity-clinics/", "/clinics/contact?clinic_name="),
        exclude_hints=(
            "/news",
            "/advertise",
            "/privacy",
            "/terms",
            "/login",
            "/tag/",
            "/category/",
            "/courses",
            "/course",
            "/join",
            "/about",
            "/blog",
            "/search",
            "/register",
            "/clinic-client",
            "/corporate",
            "/membership",
            "/private",
            "/vendor",
        ),
        max_pages=350,
        max_depth=4,
    ),
    "biohacking_map": SourceConfig(
        slug="biohacking_map",
        name="The Biohacking Map",
        seeds=("https://thebiohackingmap.com/directory/", "https://thebiohackingmap.com/api/clinics"),
        listing_hints=("/directory/", "/clinic/", "/listing/", "/place/"),
        follow_hints=("/directory", "/clinic", "/listing", "/place", "/location", "/category"),
        exclude_hints=("/blog", "/privacy", "/terms", "/login", "/account"),
        max_pages=500,
        max_depth=4,
    ),
    "world_longevity_clinics": SourceConfig(
        slug="world_longevity_clinics",
        name="World Longevity Clinics",
        seeds=("https://worldlongevityclinics.com/",),
        listing_hints=("/clinic", "/clinics", "/listing", "/directory", "/locations"),
        follow_hints=("/clinic", "/clinics", "/listing", "/directory", "/locations"),
        exclude_hints=("/blog", "/privacy", "/terms", "/login", "/cart", "/checkout", "/compare", "-vs-", "-alternatives"),
        max_pages=350,
        max_depth=4,
    ),
    "immortality_clinic": SourceConfig(
        slug="immortality_clinic",
        name="Immortality Clinic",
        seeds=("https://immortalityclinic.com/",),
        listing_hints=("/clinic", "/clinics", "/longevity", "/services", "/treatments"),
        follow_hints=("/clinic", "/clinics", "/longevity", "/services", "/treatments", "/locations"),
        exclude_hints=("/blog", "/privacy", "/terms", "/login", "/cart", "/checkout"),
        max_pages=250,
        max_depth=3,
    ),
    "longevity_lion": SourceConfig(
        slug="longevity_lion",
        name="Longevity Lion",
        seeds=("https://longevitylion.com/",),
        listing_hints=("/clinic", "/clinics", "/directory", "/listing", "/places"),
        follow_hints=("/clinic", "/clinics", "/directory", "/listing", "/places", "/location"),
        exclude_hints=("/blog", "/privacy", "/terms", "/login", "/sign"),
        max_pages=350,
        max_depth=4,
    ),
    "bookimed_longevity": SourceConfig(
        slug="bookimed_longevity",
        name="Bookimed Longevity Health",
        seeds=tuple(
            ["https://us-uk.bookimed.com/clinics/direction=longevity-health/best/"]
            + [
                f"https://us-uk.bookimed.com/clinics/direction=longevity-health/best/page={page}/"
                for page in range(2, 27)
            ]
        ),
        listing_hints=("/clinic/", "/clinics/", "/doctors/"),
        follow_hints=("/clinic/",),
        exclude_hints=(
            "/blog",
            "/privacy",
            "/terms",
            "/login",
            "/sign",
            "/about",
            "/doctors",
            "/clinics/country",
            "/clinics/procedure",
            "/clinics/illness",
            "/page/",
        ),
        max_pages=500,
        max_depth=4,
        delay_seconds=0.2,
        allowed_domains=("bookimed.com", "us-uk.bookimed.com"),
    ),
    "exec_health": SourceConfig(
        slug="exec_health",
        name="Executive Health",
        seeds=("https://www.exechealth.org",),
        listing_hints=("/directory", "/provider", "/clinic", "/clinics", "/locations", "/program"),
        follow_hints=("/provider", "/clinic", "/clinics", "/locations", "/program", "/directory"),
        exclude_hints=("/blog", "/privacy", "/terms", "/login", "/cart", "/checkout"),
        max_pages=250,
        max_depth=3,
    ),
    "human_longevity": SourceConfig(
        slug="human_longevity",
        name="Human Longevity",
        seeds=("https://www.humanlongevity.com/",),
        listing_hints=("/location", "/locations", "/program", "/services", "/health-nucleus"),
        follow_hints=("/location", "/locations", "/program", "/services", "/health-nucleus", "/contact"),
        exclude_hints=("/blog", "/privacy", "/terms", "/login", "/cart", "/checkout"),
        max_pages=250,
        max_depth=3,
    ),
    "classpass_wellness": SourceConfig(
        slug="classpass_wellness",
        name="ClassPass Wellness Recovery Search",
        seeds=tuple(
            f"https://classpass.com/search/{market}/{category}?radius=25"
            for market in TOP_US_CLASSPASS_MARKETS
            for category in CLASSPASS_WELLNESS_CATEGORIES
        ),
        listing_hints=("/search/",),
        follow_hints=(),
        exclude_hints=(),
        max_pages=len(TOP_US_CLASSPASS_MARKETS) * len(CLASSPASS_WELLNESS_CATEGORIES),
        max_depth=0,
        delay_seconds=0.2,
        allowed_domains=("classpass.com",),
    ),
    "zocdoc_specialists": SourceConfig(
        slug="zocdoc_specialists",
        name="Zocdoc Specialist Directories",
        seeds=(
            "https://www.zocdoc.com/sports-medicine-specialists",
            "https://www.zocdoc.com/radiologists",
            "https://www.zocdoc.com/sleep-medicine-specialists",
            "https://www.zocdoc.com/plastic-surgeons",
        ),
        listing_hints=(
            "/sports-medicine-specialists",
            "/radiologists",
            "/sleep-medicine-specialists",
            "/plastic-surgeons",
        ),
        follow_hints=(),
        exclude_hints=(),
        max_pages=4,
        max_depth=0,
        delay_seconds=0.2,
        allowed_domains=("zocdoc.com",),
    ),
    "realself_providers": SourceConfig(
        slug="realself_providers",
        name="RealSelf Provider Directory",
        seeds=tuple(
            f"https://www.realself.com/find/{state}/{city}/{provider_type}"
            for state, city in REALSELF_CITIES
            for provider_type in REALSELF_PROVIDER_TYPES
        ),
        listing_hints=("/find/", "/dr/"),
        follow_hints=("/dr/",),
        exclude_hints=("/reviews", "/questions", "/photos", "/forum", "/news"),
        max_pages=1200,
        max_depth=1,
        delay_seconds=1.5,
        allowed_domains=("realself.com",),
    ),
    "a4m_find_doctor": SourceConfig(
        slug="a4m_find_doctor",
        name="A4M Find a Doctor",
        seeds=(
            "https://www.a4m.com/find-a-doctor.html",
            "https://www.a4m.com/robots.txt",
            "https://www.a4m.com/sitemap.xml",
            "https://www.a4m.com/simar-randhawa-wellnessmd-new-york-ny-2.html",
            "https://www.a4m.com/yekaterina-kuznetsova-functional-medicine-nyc-new-york-city-ny.html",
            "https://www.a4m.com/dr-andrew-kibert-doctor-k-private-medicine-pllc-new-york-ny.html",
        ),
        listing_hints=("/find-a-doctor",),
        follow_hints=(),
        exclude_hints=(),
        max_pages=6,
        max_depth=0,
        delay_seconds=0.2,
    ),
    "longevitydocs_directory": SourceConfig(
        slug="longevitydocs_directory",
        name="LongevityDocs Physician Directory",
        seeds=("https://longevitydocs.org/pages/welcome-directory",),
        listing_hints=("/pages/welcome-directory",),
        follow_hints=(),
        exclude_hints=("/cart", "/account", "/customer_authentication", "/search"),
        max_pages=1,
        max_depth=0,
        delay_seconds=0.2,
    ),
    "bioedge_clinics": SourceConfig(
        slug="bioedge_clinics",
        name="bioEDGE Longevity Clinics",
        seeds=tuple(
            ["https://bioedgelongevity.com/clinics"]
            + [f"https://bioedgelongevity.com/clinics?page={page}" for page in range(2, 100)]
        ),
        listing_hints=("/clinics/",),
        follow_hints=("/clinics",),
        exclude_hints=("/articles", "/news", "/library", "/what-is", "/leaders", "/solutions"),
        max_pages=5000,
        max_depth=4,
        delay_seconds=0.05,
    ),
    "concierge_doctors_near_me": SourceConfig(
        slug="concierge_doctors_near_me",
        name="Concierge Doctors Near Me",
        seeds=tuple(
            ["https://conciergedoctorsnearme.com/listings/"]
            + [f"https://conciergedoctorsnearme.com/listings/page/{page}/" for page in range(2, 99)]
        ),
        listing_hints=("/listing/", "/listings/"),
        follow_hints=("/listing/", "/listings/"),
        exclude_hints=(
            "/blog",
            "/privacy",
            "/terms",
            "/wp-login",
            "/cart",
            "/checkout",
            "/region/",
            "/listing-category/",
            "/add-your-practice",
            "/bookmarks",
            "/reviews",
        ),
        max_pages=1500,
        max_depth=2,
        delay_seconds=0.05,
    ),
    "best_executive_physical_programs": SourceConfig(
        slug="best_executive_physical_programs",
        name="Best Executive Physical Programs",
        seeds=("https://bestexecutivephysicalprograms.com/",),
        listing_hints=("/",),
        follow_hints=(),
        exclude_hints=(),
        max_pages=1,
        max_depth=0,
        delay_seconds=0.2,
    ),
    "bookimed_longevity_doctors": SourceConfig(
        slug="bookimed_longevity_doctors",
        name="Bookimed Longevity Health Doctors",
        seeds=tuple(
            ["https://us-uk.bookimed.com/doctors/direction=longevity-health/"]
            + [
                f"https://us-uk.bookimed.com/doctors/direction=longevity-health/page={page}/"
                for page in range(2, 7)
            ]
        ),
        listing_hints=("/doctor/", "/doctors/direction=longevity-health"),
        follow_hints=("/doctor/", "/doctors/direction=longevity-health"),
        exclude_hints=(
            "/blog",
            "/privacy",
            "/terms",
            "/login",
            "/sign",
            "/clinic/",
            "/clinics/",
            "/doctors/country",
            "/doctors/procedure",
            "/doctors/illness",
        ),
        max_pages=150,
        max_depth=2,
        delay_seconds=0.15,
        allowed_domains=("bookimed.com", "us-uk.bookimed.com"),
    ),
    "stem_cell_authority": SourceConfig(
        slug="stem_cell_authority",
        name="Stem Cell Authority Business Directory",
        seeds=tuple(
            ["https://stemcellauthority.com/business-directory/?wpbdp_view=all_listings"]
            + [
                f"https://stemcellauthority.com/business-directory/page/{page}/?wpbdp_view=all_listings"
                for page in range(2, 801)
            ]
        ),
        listing_hints=("/business-directory/",),
        follow_hints=("/business-directory/",),
        exclude_hints=(
            "/blogs",
            "/business-directory/location/",
            "/business-directory/wpbdp_tag/",
            "/business-directory/?dosrch=",
            "/business-directory/?wpbdp_view=search",
            "/business-directory/?wpbdp_view=submit_listing",
        ),
        max_pages=900,
        max_depth=3,
        delay_seconds=0.05,
    ),
    "mayo_executive_health_locations": SourceConfig(
        slug="mayo_executive_health_locations",
        name="Mayo Clinic Executive Health Locations",
        seeds=("https://www.mayoclinic.org/executive-health/locations",),
        listing_hints=("/executive-health/locations",),
        follow_hints=("/executive-health/locations",),
        exclude_hints=("/appointments", "/about-mayo-clinic", "/diseases-conditions", "/tests-procedures"),
        max_pages=10,
        max_depth=2,
        delay_seconds=0.2,
    ),
    "fountain_life_best_longevity_clinics_blog": SourceConfig(
        slug="fountain_life_best_longevity_clinics_blog",
        name="Fountain Life Best Longevity Clinics Blog",
        seeds=("https://www.fountainlife.com/blog/best-longevity-clinics-in-the-world/",),
        listing_hints=("/blog/best-longevity-clinics-in-the-world",),
        follow_hints=(),
        exclude_hints=(),
        max_pages=1,
        max_depth=0,
        delay_seconds=0.2,
    ),
}


SOURCES.update(
    {
        "bookimed_longevity_turkey": SourceConfig(
            slug="bookimed_longevity_turkey",
            name="Bookimed Longevity Health Clinics - Turkey",
            seeds=_paged_urls("https://us-uk.bookimed.com/clinics/country=turkey/direction=longevity-health/best/", 10),
            listing_hints=("/clinic/", "/clinics/country=turkey/direction=longevity-health"),
            follow_hints=("/clinic/",),
            exclude_hints=("/blog", "/privacy", "/terms", "/login", "/sign", "/about", "/doctors", "/clinics/procedure", "/clinics/illness"),
            max_pages=180,
            max_depth=2,
            delay_seconds=0.15,
            allowed_domains=("bookimed.com", "us-uk.bookimed.com"),
        ),
        "bookimed_longevity_thailand": SourceConfig(
            slug="bookimed_longevity_thailand",
            name="Bookimed Longevity Health Clinics - Thailand",
            seeds=_paged_urls("https://us-uk.bookimed.com/clinics/country=thailand/direction=longevity-health/best/", 6),
            listing_hints=("/clinic/", "/clinics/country=thailand/direction=longevity-health"),
            follow_hints=("/clinic/",),
            exclude_hints=("/blog", "/privacy", "/terms", "/login", "/sign", "/about", "/doctors", "/clinics/procedure", "/clinics/illness"),
            max_pages=120,
            max_depth=2,
            delay_seconds=0.15,
            allowed_domains=("bookimed.com", "us-uk.bookimed.com"),
        ),
        "bookimed_longevity_korea": SourceConfig(
            slug="bookimed_longevity_korea",
            name="Bookimed Longevity Health Clinics - Republic of Korea",
            seeds=_paged_urls("https://us-uk.bookimed.com/clinics/country=republic-of-korea/direction=longevity-health/", 8),
            listing_hints=("/clinic/", "/clinics/country=republic-of-korea/direction=longevity-health"),
            follow_hints=("/clinic/",),
            exclude_hints=("/blog", "/privacy", "/terms", "/login", "/sign", "/about", "/doctors", "/clinics/procedure", "/clinics/illness"),
            max_pages=150,
            max_depth=2,
            delay_seconds=0.15,
            allowed_domains=("bookimed.com", "us-uk.bookimed.com"),
        ),
        "bookimed_longevity_doctors_turkey": SourceConfig(
            slug="bookimed_longevity_doctors_turkey",
            name="Bookimed Longevity Health Doctors - Turkey",
            seeds=_paged_urls("https://us-uk.bookimed.com/doctors/country=turkey/direction=longevity-health/", 5),
            listing_hints=("/doctor/", "/doctors/country=turkey/direction=longevity-health"),
            follow_hints=("/doctor/",),
            exclude_hints=("/blog", "/privacy", "/terms", "/login", "/sign", "/clinic/", "/clinics/", "/doctors/procedure", "/doctors/illness"),
            max_pages=120,
            max_depth=2,
            delay_seconds=0.15,
            allowed_domains=("bookimed.com", "us-uk.bookimed.com"),
        ),
        "bookimed_longevity_doctors_thailand": SourceConfig(
            slug="bookimed_longevity_doctors_thailand",
            name="Bookimed Longevity Health Doctors - Thailand",
            seeds=_paged_urls("https://us-uk.bookimed.com/doctors/country=thailand/direction=longevity-health/", 5),
            listing_hints=("/doctor/", "/doctors/country=thailand/direction=longevity-health"),
            follow_hints=("/doctor/",),
            exclude_hints=("/blog", "/privacy", "/terms", "/login", "/sign", "/clinic/", "/clinics/", "/doctors/procedure", "/doctors/illness"),
            max_pages=100,
            max_depth=2,
            delay_seconds=0.15,
            allowed_domains=("bookimed.com", "us-uk.bookimed.com"),
        ),
        "bookimed_longevity_doctors_korea": SourceConfig(
            slug="bookimed_longevity_doctors_korea",
            name="Bookimed Longevity Health Doctors - Republic of Korea",
            seeds=_paged_urls("https://us-uk.bookimed.com/doctors/country=republic-of-korea/direction=longevity-health/", 5),
            listing_hints=("/doctor/", "/doctors/country=republic-of-korea/direction=longevity-health"),
            follow_hints=("/doctor/",),
            exclude_hints=("/blog", "/privacy", "/terms", "/login", "/sign", "/clinic/", "/clinics/", "/doctors/procedure", "/doctors/illness"),
            max_pages=100,
            max_depth=2,
            delay_seconds=0.15,
            allowed_domains=("bookimed.com", "us-uk.bookimed.com"),
        ),
        "mymeditravel_regenerative_thailand": SourceConfig(
            slug="mymeditravel_regenerative_thailand",
            name="MyMediTravel Regenerative Medicine Clinics - Thailand",
            seeds=("https://www.mymeditravel.com/regenerative-medicine-clinics-in-thailand",),
            listing_hints=("/regenerative-medicine-clinics-in-thailand", "/medical-centers/"),
            follow_hints=("/medical-centers/",),
            exclude_hints=("/procedures/", "/forum", "/blog", "/sign"),
            max_pages=90,
            max_depth=1,
            delay_seconds=0.1,
            allowed_domains=("mymeditravel.com", "media.mymeditravel.com"),
        ),
        "mymeditravel_antiaging_stemcell_thailand": SourceConfig(
            slug="mymeditravel_antiaging_stemcell_thailand",
            name="MyMediTravel Anti-Aging Stem Cell Treatment - Thailand",
            seeds=("https://www.mymeditravel.com/antiaging-stem-cell-treatment-procedures-in-thailand",),
            listing_hints=("/antiaging-stem-cell-treatment-procedures-in-thailand", "/medical-centers/"),
            follow_hints=("/medical-centers/",),
            exclude_hints=("/procedures/", "/forum", "/blog", "/sign"),
            max_pages=90,
            max_depth=1,
            delay_seconds=0.1,
            allowed_domains=("mymeditravel.com", "media.mymeditravel.com"),
        ),
        "mymeditravel_antiaging_stemcell_bangkok": SourceConfig(
            slug="mymeditravel_antiaging_stemcell_bangkok",
            name="MyMediTravel Anti-Aging Stem Cell Treatment - Bangkok",
            seeds=("https://www.mymeditravel.com/antiaging-stem-cell-treatment-procedures-in-bangkok-thailand",),
            listing_hints=("/antiaging-stem-cell-treatment-procedures-in-bangkok-thailand", "/medical-centers/"),
            follow_hints=("/medical-centers/",),
            exclude_hints=("/procedures/", "/forum", "/blog", "/sign"),
            max_pages=80,
            max_depth=1,
            delay_seconds=0.1,
            allowed_domains=("mymeditravel.com", "media.mymeditravel.com"),
        ),
        "mymeditravel_regenerative_southkorea": SourceConfig(
            slug="mymeditravel_regenerative_southkorea",
            name="MyMediTravel Regenerative Medicine Clinics - South Korea",
            seeds=("https://www.mymeditravel.com/regenerative-medicine-clinics-in-southkorea",),
            listing_hints=("/regenerative-medicine-clinics-in-southkorea", "/medical-centers/"),
            follow_hints=("/medical-centers/",),
            exclude_hints=("/procedures/", "/forum", "/blog", "/sign"),
            max_pages=80,
            max_depth=1,
            delay_seconds=0.1,
            allowed_domains=("mymeditravel.com", "media.mymeditravel.com"),
        ),
        "mymeditravel_chaum_medical_center": SourceConfig(
            slug="mymeditravel_chaum_medical_center",
            name="MyMediTravel Chaum Medical Center",
            seeds=("https://www.mymeditravel.com/medical-centers/southkorea/seoul/dogok-dong/chaum-medical-center",),
            listing_hints=("/medical-centers/southkorea/seoul/dogok-dong/chaum-medical-center",),
            follow_hints=(),
            exclude_hints=(),
            max_pages=1,
            max_depth=0,
            delay_seconds=0.1,
            allowed_domains=("mymeditravel.com", "media.mymeditravel.com"),
        ),
        "mymeditravel_regenerative_turkey": SourceConfig(
            slug="mymeditravel_regenerative_turkey",
            name="MyMediTravel Regenerative Medicine Clinics - Turkey",
            seeds=("https://www.mymeditravel.com/regenerative-medicine-clinics-in-turkey",),
            listing_hints=("/regenerative-medicine-clinics-in-turkey", "/medical-centers/"),
            follow_hints=("/medical-centers/",),
            exclude_hints=("/procedures/", "/forum", "/blog", "/sign"),
            max_pages=80,
            max_depth=1,
            delay_seconds=0.1,
            allowed_domains=("mymeditravel.com", "media.mymeditravel.com"),
        ),
        "mymeditravel_antiaging_stemcell_turkey": SourceConfig(
            slug="mymeditravel_antiaging_stemcell_turkey",
            name="MyMediTravel Anti-Aging Stem Cell Treatment - Turkey",
            seeds=("https://www.mymeditravel.com/antiaging-stem-cell-treatment-procedures-in-turkey",),
            listing_hints=("/antiaging-stem-cell-treatment-procedures-in-turkey", "/medical-centers/"),
            follow_hints=("/medical-centers/",),
            exclude_hints=("/procedures/", "/forum", "/blog", "/sign"),
            max_pages=80,
            max_depth=1,
            delay_seconds=0.1,
            allowed_domains=("mymeditravel.com", "media.mymeditravel.com"),
        ),
        "placidway_antiaging_turkey": SourceConfig(
            slug="placidway_antiaging_turkey",
            name="PlacidWay Anti-Aging Medical Centers - Turkey",
            seeds=("https://www.placidway.com/search-medical-centers/Anti-Aging/Turkey/1",),
            listing_hints=("/search-medical-centers/Anti-Aging/Turkey", "/profile/"),
            follow_hints=("/profile/",),
            exclude_hints=("/package/", "/view-review/", "/search-medical-doctors/"),
            max_pages=80,
            max_depth=1,
            delay_seconds=0.1,
            allowed_domains=("placidway.com", "www.placidway.com"),
        ),
        "placidway_antiaging_thailand": SourceConfig(
            slug="placidway_antiaging_thailand",
            name="PlacidWay Anti-Aging Medical Centers - Thailand",
            seeds=("https://www.placidway.com/search-medical-centers/Anti-Aging/Thailand/1",),
            listing_hints=("/search-medical-centers/Anti-Aging/Thailand", "/profile/"),
            follow_hints=("/profile/",),
            exclude_hints=("/package/", "/view-review/", "/search-medical-doctors/"),
            max_pages=80,
            max_depth=1,
            delay_seconds=0.1,
            allowed_domains=("placidway.com", "www.placidway.com"),
        ),
        "placidway_antiaging_south_korea": SourceConfig(
            slug="placidway_antiaging_south_korea",
            name="PlacidWay Anti-Aging Medical Centers - South Korea",
            seeds=("https://www.placidway.com/search-medical-centers/Anti-Aging/South-Korea/1",),
            listing_hints=("/search-medical-centers/Anti-Aging/South-Korea", "/profile/"),
            follow_hints=("/profile/",),
            exclude_hints=("/package/", "/view-review/", "/search-medical-doctors/"),
            max_pages=80,
            max_depth=1,
            delay_seconds=0.1,
            allowed_domains=("placidway.com", "www.placidway.com"),
        ),
        "placidway_stem_cell_turkey": SourceConfig(
            slug="placidway_stem_cell_turkey",
            name="PlacidWay Stem Cell Therapy Medical Centers - Turkey",
            seeds=("https://www.placidway.com/search-medical-centers/Stem-Cell-Therapy/Turkey/1",),
            listing_hints=("/search-medical-centers/Stem-Cell-Therapy/Turkey", "/profile/"),
            follow_hints=("/profile/",),
            exclude_hints=("/package/", "/view-review/", "/search-medical-doctors/"),
            max_pages=80,
            max_depth=1,
            delay_seconds=0.1,
            allowed_domains=("placidway.com", "www.placidway.com"),
        ),
        "placidway_stem_cell_thailand": SourceConfig(
            slug="placidway_stem_cell_thailand",
            name="PlacidWay Stem Cell Therapy Medical Centers - Thailand",
            seeds=("https://www.placidway.com/search-medical-centers/Stem-Cell-Therapy/Thailand/1",),
            listing_hints=("/search-medical-centers/Stem-Cell-Therapy/Thailand", "/profile/"),
            follow_hints=("/profile/",),
            exclude_hints=("/package/", "/view-review/", "/search-medical-doctors/"),
            max_pages=80,
            max_depth=1,
            delay_seconds=0.1,
            allowed_domains=("placidway.com", "www.placidway.com"),
        ),
        "placidway_stem_cell_south_korea": SourceConfig(
            slug="placidway_stem_cell_south_korea",
            name="PlacidWay Stem Cell Therapy Medical Centers - South Korea",
            seeds=("https://www.placidway.com/search-medical-centers/Stem-Cell-Therapy/South-Korea/1",),
            listing_hints=("/search-medical-centers/Stem-Cell-Therapy/South-Korea", "/profile/"),
            follow_hints=("/profile/",),
            exclude_hints=("/package/", "/view-review/", "/search-medical-doctors/"),
            max_pages=80,
            max_depth=1,
            delay_seconds=0.1,
            allowed_domains=("placidway.com", "www.placidway.com"),
        ),
        "medical_travel_market_longevity_programs": SourceConfig(
            slug="medical_travel_market_longevity_programs",
            name="Medical Travel Market Longevity Programs",
            seeds=_path_pages("https://medicaltravelmarket.com/wellness/longevity-programs", 3),
            listing_hints=("/wellness/longevity-programs", "/wellness-package/"),
            follow_hints=("/wellness-package/"),
            exclude_hints=("/news/", "/join-", "/wp-", "/tag/"),
            max_pages=80,
            max_depth=1,
            delay_seconds=0.1,
        ),
        "turkey_health_tourism_authorized_providers": SourceConfig(
            slug="turkey_health_tourism_authorized_providers",
            name="Turkey Health Tourism Authorized Providers",
            seeds=("https://shgmturizmdb.saglik.gov.tr/EN-69289/healthcare-providers-with-international-health-tourism-authorization-certificates.html",),
            listing_hints=("/EN-69289/", "/EN,69063/", "/TR-9483"),
            follow_hints=("/TR-94834/", "/TR-94835/", "/TR-94836/", "/TR-94837/", "dosyamerkez.saglik.gov.tr"),
            exclude_hints=(),
            max_pages=12,
            max_depth=2,
            delay_seconds=0.15,
            allowed_domains=("saglik.gov.tr", "shgmturizmdb.saglik.gov.tr", "saglikturizmi.saglik.gov.tr", "dosyamerkez.saglik.gov.tr"),
        ),
        "longevity_suite_istanbul_biohacking": SourceConfig(
            slug="longevity_suite_istanbul_biohacking",
            name="The Longevity Suite Istanbul Biohacking Clinic",
            seeds=("https://thelongevitysuite.com/en/centres/istanbul-biohacking-clinic/",),
            listing_hints=("/en/centres/istanbul-biohacking-clinic",),
            follow_hints=(),
            exclude_hints=(),
            max_pages=1,
            max_depth=0,
            delay_seconds=0.2,
        ),
        "turkey_healthcare_group_regenerative": SourceConfig(
            slug="turkey_healthcare_group_regenerative",
            name="Turkey Healthcare Group Regenerative Therapy Centre",
            seeds=("https://en.turkeyhealthcaregroup.com/department/regenerative-therapy-centre/",),
            listing_hints=("/department/regenerative-therapy-centre",),
            follow_hints=(),
            exclude_hints=(),
            max_pages=1,
            max_depth=0,
            delay_seconds=0.2,
            allowed_domains=("en.turkeyhealthcaregroup.com", "www.en.turkeyhealthcaregroup.com"),
        ),
        "istanbul_stem_cell_aging": SourceConfig(
            slug="istanbul_stem_cell_aging",
            name="Istanbul StemCell Anti-Aging Treatments",
            seeds=("https://www.istanbulstemcell.com/aging",),
            listing_hints=("/aging",),
            follow_hints=(),
            exclude_hints=(),
            max_pages=1,
            max_depth=0,
            delay_seconds=0.2,
        ),
        "istanbul_med_assist_stem_cell_longevity": SourceConfig(
            slug="istanbul_med_assist_stem_cell_longevity",
            name="Istanbul Med Assist Stem Cell Longevity Packages",
            seeds=("https://www.istanbulmedassist.com/stem-cell-longevity-packages/",),
            listing_hints=("/stem-cell-longevity-packages",),
            follow_hints=(),
            exclude_hints=(),
            max_pages=1,
            max_depth=0,
            delay_seconds=0.2,
        ),
        "uniclinics_turkey_clinics": SourceConfig(
            slug="uniclinics_turkey_clinics",
            name="Uniclinics Turkey Clinics",
            seeds=("https://en.uniclinics.com/medical-tourism/turkey/clinics/",),
            listing_hints=("/medical-tourism/turkey/clinics/",),
            follow_hints=("/medical-tourism/turkey/clinics/"),
            exclude_hints=("/privacy", "/diagnoses-and-prices", "/treatment-in-turkey"),
            max_pages=80,
            max_depth=1,
            delay_seconds=0.1,
            allowed_domains=("en.uniclinics.com", "uniclinics.com"),
        ),
        "longevita_clinics": SourceConfig(
            slug="longevita_clinics",
            name="Longevita Hospitals and Clinics",
            seeds=("https://www.longevita.co.uk/", "https://www.longevita.co.uk/hospitals-and-clinics/"),
            listing_hints=("/", "/hospitals-and-clinics/"),
            follow_hints=(),
            exclude_hints=(),
            max_pages=2,
            max_depth=0,
            delay_seconds=0.2,
        ),
        "bookinghealth_turkey_clinics": SourceConfig(
            slug="bookinghealth_turkey_clinics",
            name="Booking Health Turkey Clinics",
            seeds=("https://www.bookinghealth.com/clinics/turkey",),
            listing_hints=("/clinics/turkey",),
            follow_hints=(),
            exclude_hints=(),
            max_pages=1,
            max_depth=0,
            delay_seconds=0.2,
            allowed_domains=("bookinghealth.com", "www.bookinghealth.com"),
        ),
        "thailand_longevity_guidebook_pdf": SourceConfig(
            slug="thailand_longevity_guidebook_pdf",
            name="Thailand A Paradise for Longevity PDF",
            seeds=("https://amazingthailand.com.au/wp-content/uploads/2018/10/1_Medical-Guidebook-Thailand-A-Paradise-for-Longevity.pdf",),
            listing_hints=(".pdf",),
            max_pages=1,
            max_depth=0,
            delay_seconds=0.2,
        ),
        "healing_harmony_thailand_pdf": SourceConfig(
            slug="healing_harmony_thailand_pdf",
            name="Healing Harmony Thailand PDF",
            seeds=("https://www.turismotailandes.com/wp-content/uploads/2015/05/HealingHarmonyHi-Res11.pdf",),
            listing_hints=(".pdf",),
            max_pages=1,
            max_depth=0,
            delay_seconds=0.2,
        ),
        "gangnam_medical_tourism": SourceConfig(
            slug="gangnam_medical_tourism",
            name="Gangnam Medical Tourism Clinics",
            seeds=("https://medicaltour.gangnam.go.kr/2021/content/clinic.do",),
            listing_hints=("/2021/content/clinic.do", "/2021/content/clinicDetail.do"),
            follow_hints=("/2021/content/clinicDetail.do"),
            exclude_hints=("/notice", "/gallery", "/hotels"),
            max_pages=180,
            max_depth=1,
            delay_seconds=0.05,
            allowed_domains=("medicaltour.gangnam.go.kr",),
        ),
        "seoul_guide_medical": SourceConfig(
            slug="seoul_guide_medical",
            name="Seoul Guide Medical",
            seeds=("https://seoulguidemedical.com/",),
            listing_hints=("/",),
            follow_hints=(),
            exclude_hints=(),
            max_pages=1,
            max_depth=0,
            delay_seconds=0.2,
        ),
        "korea_health_pages_medical_tourism_services": SourceConfig(
            slug="korea_health_pages_medical_tourism_services",
            name="Korea Health Pages Medical Tourism Services",
            seeds=("https://koreahealthpages.com/korea/health-medical-tourism-services-korea", "https://koreahealthpages.com/korea/health-medical-tourism-services-korea/p:2"),
            listing_hints=("/korea/health-medical-tourism-services-korea", "/korea/"),
            follow_hints=("/korea/"),
            exclude_hints=("/article/", "/blog", "/contact", "/advertise"),
            max_pages=60,
            max_depth=1,
            delay_seconds=0.1,
        ),
        "korea_health_pages_anti_aging_gangnam": SourceConfig(
            slug="korea_health_pages_anti_aging_gangnam",
            name="Korea Health Pages Anti-Aging Clinic Seoul Gangnam",
            seeds=("https://koreahealthpages.com/korea/anti-aging-clinic-seoul-gangnam", "https://koreahealthpages.com/korea/anti-aging-clinic-seoul-gangnam/p:2"),
            listing_hints=("/korea/anti-aging-clinic-seoul-gangnam", "/korea/"),
            follow_hints=("/korea/"),
            exclude_hints=("/article/", "/blog", "/contact", "/advertise"),
            max_pages=60,
            max_depth=1,
            delay_seconds=0.1,
        ),
        "korea_health_pages_iv_drip": SourceConfig(
            slug="korea_health_pages_iv_drip",
            name="Korea Health Pages IV Drip Vitamin Therapy",
            seeds=(
                "https://koreahealthpages.com/korea/iv-drip-vitamin-therapy-korea",
                "https://koreahealthpages.com/korea/iv-drip-vitamin-therapy-korea/p:2",
                "https://koreahealthpages.com/korea/iv-drip-vitamin-therapy-seoul-gangnam",
                "https://koreahealthpages.com/korea/iv-drip-vitamin-therapy-seoul-gangnam/p:2",
            ),
            listing_hints=("/korea/iv-drip-vitamin-therapy-korea", "/korea/"),
            follow_hints=("/korea/"),
            exclude_hints=("/article/", "/blog", "/contact", "/advertise"),
            max_pages=60,
            max_depth=1,
            delay_seconds=0.3,
        ),
        "korea_health_pages_rejuran": SourceConfig(
            slug="korea_health_pages_rejuran",
            name="Korea Health Pages Rejuran Treatment",
            seeds=(
                "https://koreahealthpages.com/korea/rejuran-treatment-korea",
                "https://koreahealthpages.com/korea/rejuran-treatment-korea/p:2",
                "https://koreahealthpages.com/korea/rejuran-healer-clinic-seoul-gangnam",
                "https://koreahealthpages.com/korea/rejuran-healer-clinic-seoul-gangnam/p:2",
            ),
            listing_hints=("/korea/rejuran-treatment-korea", "/korea/"),
            follow_hints=("/korea/"),
            exclude_hints=("/article/", "/blog", "/contact", "/advertise"),
            max_pages=60,
            max_depth=1,
            delay_seconds=0.3,
        ),
        "korea_health_pages_prp_skin": SourceConfig(
            slug="korea_health_pages_prp_skin",
            name="Korea Health Pages PRP Skin Treatment",
            seeds=(
                "https://koreahealthpages.com/korea/prp-skin-treatment-korea",
                "https://koreahealthpages.com/korea/prp-skin-treatment-korea/p:2",
                "https://koreahealthpages.com/korea/prp-skin-treatment-seoul-gangnam",
                "https://koreahealthpages.com/korea/prp-skin-treatment-seoul-gangnam/p:2",
            ),
            listing_hints=("/korea/prp-skin-treatment-korea", "/korea/"),
            follow_hints=("/korea/"),
            exclude_hints=("/article/", "/blog", "/contact", "/advertise"),
            max_pages=60,
            max_depth=1,
            delay_seconds=0.3,
        ),
        "korea_health_pages_stem_cell": SourceConfig(
            slug="korea_health_pages_stem_cell",
            name="Korea Health Pages Stem Cell Therapy",
            seeds=(
                "https://koreahealthpages.com/korea/stem-cell-therapy-korea",
                "https://koreahealthpages.com/korea/stem-cell-therapy-korea/p:2",
                "https://koreahealthpages.com/korea/stem-cell-therapy-seoul-korea",
                "https://koreahealthpages.com/korea/stem-cell-therapy-seoul-korea/p:2",
            ),
            listing_hints=("/korea/stem-cell-therapy-korea", "/korea/"),
            follow_hints=("/korea/"),
            exclude_hints=("/article/", "/blog", "/contact", "/advertise"),
            max_pages=60,
            max_depth=1,
            delay_seconds=0.3,
        ),
        "korea_health_pages_regenerative_medicine": SourceConfig(
            slug="korea_health_pages_regenerative_medicine",
            name="Korea Health Pages Regenerative Medicine Clinics",
            seeds=(
                "https://koreahealthpages.com/korea/regenerative-medicine-clinics-korea",
                "https://koreahealthpages.com/korea/regenerative-medicine-clinics-korea/p:2",
                "https://koreahealthpages.com/korea/best-stem-cell-clinics-seoul-gangnam",
                "https://koreahealthpages.com/korea/best-stem-cell-clinics-seoul-gangnam/p:2",
            ),
            listing_hints=("/korea/regenerative-medicine-clinics-korea", "/korea/"),
            follow_hints=("/korea/"),
            exclude_hints=("/article/", "/blog", "/contact", "/advertise"),
            max_pages=60,
            max_depth=1,
            delay_seconds=0.3,
        ),
        "korea_medical_directory_pdf": SourceConfig(
            slug="korea_medical_directory_pdf",
            name="Visit Korea Medical Tourism Directory PDF",
            seeds=("https://french.visitkorea.or.kr/public/asis/contents/medical/pdf/directory_enu.pdf",),
            listing_hints=(".pdf",),
            max_pages=1,
            max_depth=0,
            delay_seconds=0.2,
        ),
        "meditrip_seoul": SourceConfig(
            slug="meditrip_seoul",
            name="Meditrip Seoul",
            seeds=("https://www.meditripseoul.com/",),
            listing_hints=("/",),
            follow_hints=(),
            exclude_hints=(),
            max_pages=1,
            max_depth=0,
            delay_seconds=0.2,
        ),
        "medical_tour_365": SourceConfig(
            slug="medical_tour_365",
            name="365 Medical Tour",
            seeds=("https://www.365medicaltour.com/",),
            listing_hints=("/",),
            follow_hints=(),
            exclude_hints=(),
            max_pages=1,
            max_depth=0,
            delay_seconds=0.2,
        ),
    }
)
